; Script generated by the HM NIS Edit Script Wizard.
; Updated to NSIS 3.04

; Standard return codes
; 0 = Installation successful
; 112 = Disk space is full
; 1602 = Installation cancelled by user
; 1618 = Another installation is already in progress
; 1625 = Package rejected during installation / blocked by policy or elevation requirements
; 1638 = Application already exists
; 1633 = Platform not supported
; 1150 = Windows version too old
; 3010 = Reboot required to complete installation

ManifestDPIAware true

RequestExecutionLevel user
Unicode true
SetCompressor /SOLID /FINAL lzma

#!define BUILD_UNINSTALLER
#!define BUILD_X64_VERSION
#!define ENABLE_DEBUG_MESSAGES

!macro DEBUG_MSG message
!ifdef ENABLE_DEBUG_MESSAGES
  MessageBox MB_OK "${message}"
!endif
!macroend

; HM NIS Edit Wizard helper defines
BrandingText "MEGA"
!define PRODUCT_NAME "MEGAsync"

VIAddVersionKey "CompanyName" "MEGA"
VIAddVersionKey "FileDescription" "MEGAsync"
VIAddVersionKey "LegalCopyright" "MEGA 2026"
VIAddVersionKey "ProductName" "MEGAsync"

!define PRODUCT_PUBLISHER "Mega Limited"
!define PRODUCT_WEB_SITE "https://mega.io"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\MEGAsync.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY_LOCAL_MACHINE HKLM
!define PRODUCT_UNINST_ROOT_KEY_CURRENT_USER HKCU
!define PRODUCT_DIR_PUBLISHER_REGPATH "Software\${PRODUCT_PUBLISHER}"
!define PRODUCT_DIR_USER_REGKEY "${PRODUCT_DIR_PUBLISHER_REGPATH}\${PRODUCT_NAME}"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"
!define CSIDL_STARTUP '0x7' ;Startup path
!define CSIDL_LOCALAPPDATA '0x1C' ;Local Application Data path
!define CSIDL_COMMON_APPDATA '0x23'

; To be defined depending on your working environment

!ifdef BUILD_X64_VERSION
!define QT_PATH "${MEGA_QTPATH}"
!define QT_DEPLOY_PATH "qt-deploy-x64"
!else
!define QT_DEPLOY_PATH "qt-deploy-x86"
!define QT_PATH "${MEGA_QTPATH}\..\x86"
 !endif

!ifdef BUILD_X64_VERSION
!define SRCDIR_MEGASYNC "built64"
!define SRCDIR_UPDATER "built64"
!else
!define SRCDIR_MEGASYNC "built32"
!define SRCDIR_UPDATER "built32"
!endif

!define SRCDIR_MEGASHELLEXT_X32 "built32"
!define SRCDIR_MEGASHELLEXT_X64 "built64"
!define MULTIUSER_MUI
!define MULTIUSER_INSTALLMODE_COMMANDLINE
!define MULTIUSER_EXECUTIONLEVEL Standard
!define MULTIUSER_EXECUTIONLEVEL_ALLUSERS
!define MULTIUSER_INSTALLMODE_DEFAULT_CURRENTUSER

!define VcRedistBasePath "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Redist\MSVC\14.42.34433"
!define VcRedist32BasePath "${VcRedistBasePath}\x86"
!define VcRedist32Path "${VcRedist32BasePath}\Microsoft.VC143.CRT"
!define VcRedist64BasePath "${VcRedistBasePath}\x64"
!define VcRedist64Path "${VcRedist64BasePath}\Microsoft.VC143.CRT"

!define WinRedistBasePath "C:\Program Files (x86)\Windows Kits\10\Redist\${WINKITVER}\ucrt\DLLs"
!define WinRedist32BasePath "${winRedistBasePath}\x86"
!define WinRedist64BasePath "${winRedistBasePath}\x64"

!define D3DRedistBasePath "C:\Program Files (x86)\Windows Kits\10\Redist\D3D"
!define D3DRedist32BasePath "${D3DRedistBasePath}\x86"
!define D3DRedist64BasePath "${D3DRedistBasePath}\x64"


; Version info: get version directly from the binary
!getdllversion "${SRCDIR_MEGASYNC}/MEGAsync.exe" Expv_
VIAddVersionKey "FileVersion" "${Expv_1}.${Expv_2}.${Expv_3}.${Expv_4}"
!ifdef VERSION_SUFFIX
VIProductVersion "${Expv_1}.${Expv_2}.${Expv_3}.${Expv_4}-${VERSION_SUFFIX}"
VIAddVersionKey "ProductVersion" "${Expv_1}.${Expv_2}.${Expv_3}.${Expv_4}-${VERSION_SUFFIX}"
!define PRODUCT_VERSION "${Expv_1}.${Expv_2}.${Expv_3}-${VERSION_SUFFIX}"
!else
VIProductVersion "${Expv_1}.${Expv_2}.${Expv_3}.${Expv_4}"
VIAddVersionKey "ProductVersion" "${Expv_1}.${Expv_2}.${Expv_3}.${Expv_4}"
!define PRODUCT_VERSION "${Expv_1}.${Expv_2}.${Expv_3}"
!endif

!define MEGA_DATA "mega.ini"
!define UNINSTALLER_NAME "uninst.exe"

!include "MUI2.nsh"
!include "Library.nsh"
!include "UAC.nsh"
!include "MultiUser.nsh"
!include "x64.nsh"
#!include "CPUFeatures.nsh"
!include "WinVer.nsh"


; MUI Settings
!define MUI_ABORTWARNING
!define MUI_CUSTOMFUNCTION_ABORT InstallerAbort
!define MUI_ICON "installer\app_ico.ico"
!define MUI_UNICON "installer\uninstall_ico.ico"

; Language Selection Dialog Settings
;!define MUI_LANGDLL_REGISTRY_ROOT ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER}
;!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
;!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Settings
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "MEGAsync"
!define MUI_FINISHPAGE_RUN ;"$INSTDIR\MEGASync.exe"
!define MUI_FINISHPAGE_RUN_FUNCTION RunFunction

var APP_NAME
var ICONS_GROUP
;var INSTALLDAY
;var EXPIRATIONDAY
var USERNAME
var CURRENT_USER_INSTDIR
var ALL_USERS_INSTDIR
var SILENT_MULTIUSER
var INSTALLED_APP_MODE
var HKLM_UninstallString
var HKCU_UninstallString
var INSTALLER_MUTEX_HANDLE

!define ERROR_INSTALL_SUCCESS 0
!define ERROR_DISK_FULL 112
!define ERROR_INSTALL_CANCELLED 1602
!define ERROR_INSTALLATION_IN_PROGRESS 1618
!define ERROR_PACKAGE_REJECTED 1625
!define ERROR_APPLICATION_ALREADY_EXISTS 1638
!define ERROR_PLATFORM_NOT_SUPPORTED 1633
!define ERROR_WINDOWS_VERSION_TOO_OLD 1150

; Installer pages
; !define MUI_FINISHPAGE_NOAUTOCLOSE
!define MUI_PAGE_CUSTOMFUNCTION_SHOW showHiDpi
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "installer\terms.txt"
!insertmacro MULTIUSER_PAGE_INSTALLMODE
!define MUI_PAGE_CUSTOMFUNCTION_PRE StartMenuPagePre
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
!undef MUI_PAGE_CUSTOMFUNCTION_PRE
!insertmacro MUI_PAGE_INSTFILES
;Page Custom RebootPage
!define MUI_PAGE_CUSTOMFUNCTION_SHOW showHiDpi
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

; Language files (the ones available in MEGASync, with locale code)
!insertmacro MUI_LANGUAGE "Afrikaans"       ;af
!insertmacro MUI_LANGUAGE "Albanian"
!insertmacro MUI_LANGUAGE "Arabic"          ;ar
!insertmacro MUI_LANGUAGE "Armenian"
!insertmacro MUI_LANGUAGE "Basque"          ;eu
!insertmacro MUI_LANGUAGE "Belarusian"
!insertmacro MUI_LANGUAGE "Bosnian"         ;bs
!insertmacro MUI_LANGUAGE "Breton"
!insertmacro MUI_LANGUAGE "Bulgarian"       ;bg
!insertmacro MUI_LANGUAGE "Catalan"         ;ca
#!insertmacro MUI_LANGUAGE "Cibemba"
!insertmacro MUI_LANGUAGE "Croatian"        ;hr
!insertmacro MUI_LANGUAGE "Czech"           ;cs
!insertmacro MUI_LANGUAGE "Danish"          ;da
!insertmacro MUI_LANGUAGE "Dutch"           ;nl
#!insertmacro MUI_LANGUAGE "Efik" 			;locale code not found
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Esperanto"
!insertmacro MUI_LANGUAGE "Estonian"
!insertmacro MUI_LANGUAGE "Farsi" 			;locale code not found
!insertmacro MUI_LANGUAGE "Finnish"         ;fi
!insertmacro MUI_LANGUAGE "French"          ;fr
!insertmacro MUI_LANGUAGE "Galician"
!insertmacro MUI_LANGUAGE "Georgian"
!insertmacro MUI_LANGUAGE "German"            ;de
!insertmacro MUI_LANGUAGE "Greek"             ;el
!insertmacro MUI_LANGUAGE "Hebrew"            ;he
#!insertmacro MUI_LANGUAGE "Hindi"             ;hi
!insertmacro MUI_LANGUAGE "Hungarian"         ;hu
!insertmacro MUI_LANGUAGE "Icelandic"
#!insertmacro MUI_LANGUAGE "Igbo"
!insertmacro MUI_LANGUAGE "Indonesian"        ;in
!insertmacro MUI_LANGUAGE "Irish"
!insertmacro MUI_LANGUAGE "Italian"           ;it
!insertmacro MUI_LANGUAGE "Japanese"          ;ja
#!insertmacro MUI_LANGUAGE "Khmer"
!insertmacro MUI_LANGUAGE "Korean"            ;ko
!insertmacro MUI_LANGUAGE "Kurdish"
!insertmacro MUI_LANGUAGE "Latvian"           ;lv
!insertmacro MUI_LANGUAGE "Lithuanian"        ;lt
!insertmacro MUI_LANGUAGE "Luxembourgish"
!insertmacro MUI_LANGUAGE "Macedonian"        ;mk
#!insertmacro MUI_LANGUAGE "Malagasy"
!insertmacro MUI_LANGUAGE "Malay"             ;ms
!insertmacro MUI_LANGUAGE "Mongolian"
!insertmacro MUI_LANGUAGE "Norwegian"         ;no
!insertmacro MUI_LANGUAGE "NorwegianNynorsk"
!insertmacro MUI_LANGUAGE "Polish"            ;pl
!insertmacro MUI_LANGUAGE "Portuguese"        ;pt
!insertmacro MUI_LANGUAGE "PortugueseBR"      ;pt_BR
!insertmacro MUI_LANGUAGE "Romanian"          ;ro
!insertmacro MUI_LANGUAGE "Russian"           ;ru
!insertmacro MUI_LANGUAGE "Serbian"
!insertmacro MUI_LANGUAGE "SerbianLatin"
#!insertmacro MUI_LANGUAGE "Sesotho"
!insertmacro MUI_LANGUAGE "SimpChinese"       ;zh_CN
!insertmacro MUI_LANGUAGE "Slovak"            ;sk
!insertmacro MUI_LANGUAGE "Slovenian"         ;sl
!insertmacro MUI_LANGUAGE "Spanish"           ;es
!insertmacro MUI_LANGUAGE "SpanishInternational"
#!insertmacro MUI_LANGUAGE "Swahili"
!insertmacro MUI_LANGUAGE "Swedish"          ;sv
#!insertmacro MUI_LANGUAGE "Tamil"
!insertmacro MUI_LANGUAGE "Thai"             ;th
!insertmacro MUI_LANGUAGE "TradChinese"      ;zh_TW
!insertmacro MUI_LANGUAGE "Turkish"          ;tr
#!insertmacro MUI_LANGUAGE "Twi"
!insertmacro MUI_LANGUAGE "Ukrainian"        ;uk
#!insertmacro MUI_LANGUAGE "Uyghur"
!insertmacro MUI_LANGUAGE "Uzbek"
!insertmacro MUI_LANGUAGE "Vietnamese"       ;vn
!insertmacro MUI_LANGUAGE "Welsh"            ;cy
#!insertmacro MUI_LANGUAGE "Yoruba"
#!insertmacro MUI_LANGUAGE "Zulu"

; mi Maori is included in MegaSync, but not here
; ee Ewe is included in MegaSync, but not here
; tl Tagalog is included in MegaSync, but not here

; MUI end ------

Name $APP_NAME
!ifdef BUILD_UNINSTALLER
OutFile "UninstallerGenerator.exe"
!else
!ifdef BUILD_X64_VERSION
OutFile "MEGAsyncSetup64.exe"
!else
OutFile "MEGAsyncSetup32.exe"
!endif
!endif

InstallDir "$PROGRAMFILES\MEGAsync"
;This attribute tells the installer to check a string in the registry, but as we don´t allow installing in other paths, InstallDir is valid
;InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails nevershow
ShowUnInstDetails nevershow

Function RunFunction
  ${UAC.CallFunctionAsUser} RunMegaSync
FunctionEnd

Function RunMegaSync
  Exec "$INSTDIR\MEGAsync.exe"
  Sleep 2000
FunctionEnd

!macro ReleaseInstallerMutex
  ${If} $INSTALLER_MUTEX_HANDLE != ""
    System::Call 'kernel32::ReleaseMutex(p $INSTALLER_MUTEX_HANDLE)'
    System::Call 'kernel32::CloseHandle(p $INSTALLER_MUTEX_HANDLE)'
    StrCpy $INSTALLER_MUTEX_HANDLE ""
  ${EndIf}
!macroend

!macro ExitWithError number message
    !if "${number}" == ""
        !error "This method needs a number. Compilation error."
    !endif

    SetErrorLevel ${number}

    ${IfNot} ${Silent}
        !if "${message}" != ""
            MessageBox mb_IconStop|mb_TopMost|mb_SetForeground "${message}"
        !endif
    ${EndIf}

    !insertmacro ReleaseInstallerMutex
    Quit
!macroend

Function AcquireInstallerMutex
  StrCpy $INSTALLER_MUTEX_HANDLE ""
  System::Call 'kernel32::CreateMutex(p 0, i 1, t "MEGAsyncInstallerMutex") p.r0'
  StrCpy $INSTALLER_MUTEX_HANDLE $0
  System::Call 'kernel32::WaitForSingleObject(p $INSTALLER_MUTEX_HANDLE, i 0) i.r1'
  ${If} $1 == 258
    !insertmacro ReleaseInstallerMutex
    !insertmacro ExitWithError ${ERROR_INSTALLATION_IN_PROGRESS} "Another installation is already in progress. Please complete that installation before proceeding."
  ${EndIf}
FunctionEnd

Function InstallerAbort
  ${UAC.Unload}
  !insertmacro ReleaseInstallerMutex
  SetErrorLevel ${ERROR_INSTALL_CANCELLED}
FunctionEnd

; Set to "1" by CleanInstallDirectory when it schedules locked leftovers for deletion on
; reboot. It survives the mid-section "SetRebootFlag false" so .onInstSuccess can restore
; the reboot requirement that reset would otherwise discard.
Var INSTALL_REBOOT_PENDING

Function .onInstSuccess
  ; Install-directory cleanup may schedule locked leftovers (or a whole ".obsolete"
  ; directory) for removal on the next boot, which raises the reboot flag. A later
  ; "SetRebootFlag false" in the install section discards that flag, so restore it here
  ; from the recorded state before deciding the exit code, so the finish page and the
  ; return value both reflect the genuine reboot requirement.
  StrCmp $INSTALL_REBOOT_PENDING "1" 0 check_reboot_flag
    SetRebootFlag true
  check_reboot_flag:
  IfRebootFlag reboot_required install_success
reboot_required:
  SetErrorLevel ${ERROR_REBOOT_REQUIRED}
  Goto done
install_success:
  SetErrorLevel ${ERROR_INSTALL_SUCCESS}
done:
  !insertmacro ReleaseInstallerMutex
FunctionEnd

Function .onInstFailed
  !insertmacro ReleaseInstallerMutex
FunctionEnd

!define CURRENT_USER_INSTALLED_APP_MODE "CurrentUser"
!define ALL_USERS_INSTALLED_APP_MODE "AllUsers"

var UNINSTDIR
var ALL_USERS_UNINSTDIR
var CURRENT_USER_UNINSTDIR

Function GetInstalledAppMode
	StrCpy $UNINSTDIR "$INSTDIR\${UNINSTALLER_NAME}"
	StrCpy $ALL_USERS_UNINSTDIR "$ALL_USERS_INSTDIR\${PRODUCT_NAME}\${UNINSTALLER_NAME}"
	StrCpy $CURRENT_USER_UNINSTDIR "$CURRENT_USER_INSTDIR\${PRODUCT_NAME}\${UNINSTALLER_NAME}"
	StrCpy $INSTALLED_APP_MODE "" ;Reset value
	
	${If} $HKLM_UninstallString != ""
		${If} $HKLM_UninstallString == $ALL_USERS_UNINSTDIR
			StrCpy $INSTALLED_APP_MODE "${ALL_USERS_INSTALLED_APP_MODE}"
		${ElseIf} $HKLM_UninstallString == $CURRENT_USER_UNINSTDIR
			StrCpy $INSTALLED_APP_MODE "${CURRENT_USER_INSTALLED_APP_MODE}"
		${EndIf}
	${EndIf}
	
	${If} $INSTALLED_APP_MODE == ""
	${AndIf} $HKCU_UninstallString != "" 
		StrCpy $INSTALLED_APP_MODE "${CURRENT_USER_INSTALLED_APP_MODE}"   
	${EndIf}
FunctionEnd

Function GetHKCUUninstallString
	ReadRegStr $HKCU_UninstallString ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_UNINST_KEY}" "UninstallString"
	ClearErrors
	FileOpen $0 "$ALL_USERS_INSTDIR\megatmp.HKCU_UninstallString.txt" w
	IfErrors done
	FileWriteUTF16LE $0 "$HKCU_UninstallString"
	FileClose $0
done:
FunctionEnd

Function ReadHKCUUninstallString
  Sleep 200
  FileOpen $R0 "$ALL_USERS_INSTDIR\megatmp.HKCU_UninstallString.txt" r
  IfErrors done
  FileReadUTF16LE $R0 "$HKCU_UninstallString"
  FileClose $R0
  Delete "$ALL_USERS_INSTDIR\megatmp.HKCU_UninstallString.txt"
done:
FunctionEnd

!macro ReadHKLMUninstallString
	ReadRegStr $HKLM_UninstallString ${PRODUCT_UNINST_ROOT_KEY_LOCAL_MACHINE} "${PRODUCT_UNINST_KEY}" "UninstallString"
!macroend

!macro GetUninstalledAppMode
	StrCpy $UNINSTDIR "$INSTDIR\${UNINSTALLER_NAME}"
    
	System::Call 'shell32::SHGetSpecialFolderPath(i $HWNDPARENT, t .r1, i ${CSIDL_COMMON_APPDATA}, i0)i.r0'
    StrCpy $ALL_USERS_INSTDIR "$1\${PRODUCT_NAME}"
	
	${If} "$INSTDIR" == "$ALL_USERS_INSTDIR"
		StrCpy $INSTALLED_APP_MODE "${ALL_USERS_INSTALLED_APP_MODE}"
    ${Else}
		StrCpy $INSTALLED_APP_MODE "${CURRENT_USER_INSTALLED_APP_MODE}"
	${EndIf}
	
!macroend

!macro RemoveLocalMachineReg
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY_LOCAL_MACHINE} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY_LOCAL_MACHINE} "${PRODUCT_DIR_REGKEY}"
!macroend

!macro CheckHKLMUninstallInfo
	StrCpy $ALL_USERS_UNINSTDIR "$ALL_USERS_INSTDIR\${PRODUCT_NAME}\${UNINSTALLER_NAME}"
	!insertmacro ReadHKLMUninstallString

	${If} $HKLM_UninstallString != ""
	${AndIf} $INSTALLED_APP_MODE != $ALL_USERS_INSTALLED_APP_MODE
	${AndIf} $HKLM_UninstallString != $ALL_USERS_UNINSTDIR
		!insertmacro RemoveLocalMachineReg
	${EndIf}
!macroend

Function StartMenuPagePre
  ${UAC.CallFunctionAsUser} StartMenuPagePreAsUser
FunctionEnd

Function StartMenuPagePreAsUser
 ${If} $MultiUser.InstallMode == "CurrentUser"
    ReadRegStr $ICONS_GROUP ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_UNINST_KEY}" "${PRODUCT_STARTMENU_REGVAL}"
  ${Else}
    ReadRegStr $ICONS_GROUP ${PRODUCT_UNINST_ROOT_KEY_LOCAL_MACHINE} "${PRODUCT_UNINST_KEY}" "${PRODUCT_STARTMENU_REGVAL}"
  ${EndIf}
  ${If} $ICONS_GROUP == ""
    StrCpy $ICONS_GROUP "MEGAsync"
  ${EndIf}
FunctionEnd

Function un.GetStartMenuPage
${If} $INSTALLED_APP_MODE == "${CURRENT_USER_INSTALLED_APP_MODE}"
  ReadRegStr $ICONS_GROUP ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_UNINST_KEY}" "${PRODUCT_STARTMENU_REGVAL}"
  SetShellVarContext current
${Else}
  ReadRegStr $ICONS_GROUP ${PRODUCT_UNINST_ROOT_KEY_LOCAL_MACHINE} "${PRODUCT_UNINST_KEY}" "${PRODUCT_STARTMENU_REGVAL}"
  SetShellVarContext all
${EndIf}
${If} $ICONS_GROUP == ""
  StrCpy $ICONS_GROUP "MEGAsync"
${EndIf}
FunctionEnd

Function CreateShortCuts
 !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\${UNINSTALLER_NAME}"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\MEGAsync.lnk" "$INSTDIR\MEGAsync.exe"
  CreateShortCut "$DESKTOP\MEGAsync.lnk" "$INSTDIR\MEGAsync.exe"
  WriteIniStr "$INSTDIR\MEGA Website.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\MEGA Website.lnk" "$INSTDIR\MEGA Website.url" "" "$INSTDIR\MEGAsync.exe" 1
  !insertmacro MUI_STARTMENU_WRITE_END
FunctionEnd

Function un.RemoveMegaShortcuts
  Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\MEGA Website.lnk"
  Delete "$INSTDIR\MEGA Website.url"
  Delete "$DESKTOP\MEGAsync.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\MEGAsync.lnk"
  System::Call 'shell32::SHGetSpecialFolderPath(i $HWNDPARENT, t .r1, i ${CSIDL_STARTUP}, i0)i.r0'
  Delete "$1\MEGAsync.lnk"
  RMDir "$SMPROGRAMS\$ICONS_GROUP"
FunctionEnd


#CUSTOM PAGE FOR SELECT USER OR ALL USERS
Var Dialog
var SelectedCheckBox
Var Checkbox1
Var Checkbox2
Var SenderValue

Function RebootPage
  ${If} ${Silent}
    Goto done
  ${EndIf}
  !insertmacro MUI_HEADER_TEXT  $(MUI_TEXT_FINISH_INFO_TITLE) $(MUI_TEXT_FINISH_INFO_TEXT)
  nsDialogs::Create 1018
  Pop $Dialog
  ${NSD_CreateLabel} 0 0 100% 24u $(MUI_TEXT_FINISH_INFO_REBOOT)
  ${NSD_CreateRadioButton} 15u 50u 100% 10u $(MUI_TEXT_FINISH_REBOOTNOW)
  Pop $checkbox1
  ${NSD_AddStyle} $checkbox1 ${WS_GROUP}
  ${NSD_OnClick} $checkbox1 onRadioClick
  ${NSD_SetState} $checkbox1 ${BST_CHECKED}
  ${NSD_CreateRadioButton} 15u 70u 100% 10u $(MUI_TEXT_FINISH_REBOOTLATER)
  Pop $checkbox2
  ${NSD_OnClick} $checkbox2 onRadioClick
  nsDialogs::Show
  strCmp $SelectedCheckBox "True" reboot
  strCmp $SelectedCheckBox "False" done
reboot:
  reboot
done:
FunctionEnd

Function onRadioClick
  Pop $SenderValue
  ${If} $SenderValue == $checkbox1
    strcpy $SelectedCheckBox "True"
  ${ElseIf} $SenderValue == $checkbox2
    strcpy $SelectedCheckBox "False"
  ${EndIf}
FunctionEnd

!macro CheckUserToRunElevated
  UserInfo::GetOriginalAccountType
  IfErrors PluginFail
  Pop $1
  StrCmp $1 "Admin" RunElevated
  StrCmp $1 "Power" RunElevated
  StrCmp $1 "User" done
  StrCmp $1 "Guest" done
  !insertmacro ExitWithError ${ERROR_INSTALL_CANCELLED} "Elevation failed. Unknown error checking account type"
  Goto done

PluginFail:
  !insertmacro ExitWithError ${ERROR_INSTALL_CANCELLED} "Error! Unable to call UserInfo plug-in!"
RunElevated:
  UAC::RunElevated
  ${Switch} $0
  ${Case} 0
    ${If} $1 = 1 ;User process. The installer has finished. Quit.
    Quit
    ${EndIf}
    ${IfThen} $3 <> 0 ${|} ${Break} ${|} ;Admin process, continue the installation
    ${If} $1 = 3 ;RunAs completed successfully, but with a non-admin user
      ;MessageBox mb_YesNo|mb_IconExclamation|mb_TopMost|mb_SetForeground "This requires admin privileges, try again" /SD IDNO IDYES uac_tryagain IDNO 0
      !insertmacro ExitWithError ${ERROR_INSTALL_CANCELLED} "This installer requires Administrator privileges. Error $0"
    ${EndIf}
  ${Case} 1223
    !insertmacro ExitWithError ${ERROR_INSTALL_CANCELLED} "This installer requires Administrator privileges. Error $0"
  ${Default}
    !insertmacro ExitWithError ${ERROR_INSTALL_CANCELLED} "This installer requires Administrator privileges. Error $0"
  ${EndSwitch}
done:
!macroend

Var BITMAP_WELCOME

Var BANNER_PATH
Function showHiDpi
    System::Call USER32::GetDpiForSystem()i.r0
    ${If} $0 U<= 0
        System::Call USER32::GetDC(i0)i.r1
        System::Call GDI32::GetDeviceCaps(ir1,i88)i.r0
        System::Call USER32::ReleaseDC(i0,ir1)
    ${EndIf}

    ${if} $0 > 288
        StrCpy $0 288
    ${ElseIf} $0 < 72
        StrCpy $0 72
    ${EndIf}

    strCpy $BITMAP_WELCOME "$BANNER_PATH\leftbanner\left_banner$0.bmp"

    ${NSD_SetImage} $mui.WelcomePage.Image $BITMAP_WELCOME  $mui.WelcomePage.Image.Bitmap
    ${NSD_SetImage} $mui.FinishPage.Image $BITMAP_WELCOME $mui.FinishPage.Image.Bitmap

FunctionEnd

Function .onInit
  setRebootFlag false

  #Get params when silent installation is launched
  ${If} ${Silent}
     ${GetParameters} $R0
	ClearErrors
	${GetOptions} $R0 "/MULTIUSER" $0
	${IfNot} ${Errors}
		StrCpy $SILENT_MULTIUSER "true"
		StrCpy $MultiUser.InstallMode "AllUsers"
	${Else}
		StrCpy $SILENT_MULTIUSER "false"
		StrCpy $MultiUser.InstallMode "CurrentUser"
	${EndIf}
  ${Else}
	!insertmacro MULTIUSER_INIT
  ${EndIf}
  
  StrCpy $APP_NAME "${PRODUCT_NAME} ${PRODUCT_VERSION}"

  !ifdef BUILD_UNINSTALLER
         WriteUninstaller "$EXEDIR\${UNINSTALLER_NAME}"
         Quit
  !endif

  !ifdef BUILD_X64_VERSION
  ${If} ${RunningX64}
  ${Else}
    !insertmacro ExitWithError ${ERROR_PLATFORM_NOT_SUPPORTED} "This is an installer for 64-bit MEGA Desktop App, but you are using a 32-bit Windows. Please, download the 32-bit MEGA Desktop App version from https://mega.io/desktop."
  ${EndIf}
  !endif

  ${IfNot} ${AtLeastWin10}
	!insertmacro ExitWithError ${ERROR_WINDOWS_VERSION_TOO_OLD} "This MEGA Desktop App installer is for Windows 10 or above"
  ${EndIf}

  ;${GetTime} "" "L" $0 $1 $2 $3 $4 $5 $6
  ;strCpy $INSTALLDAY "$2$1$0"
  ;strCpy $EXPIRATIONDAY "20140121"

  ;${if} $INSTALLDAY >= $EXPIRATIONDAY
  ;    MessageBox mb_IconInformation|mb_TopMost|mb_SetForeground "Thank you for testing MEGAsync.$\r$\nThis beta version is no longer current and has expired.$\r$\nPlease follow @MEGAprivacy on Twitter for updates."
  ;    abort
  ;${EndIf}
  
  !insertmacro CheckUserToRunElevated
  Call AcquireInstallerMutex

  InitPluginsDir
  StrCpy $BANNER_PATH "$PLUGINSDIR"
  SetOutPath "$BANNER_PATH\leftbanner"
  File "installer\leftbanner\*"
  SetOutPath "$TEMP"

  ;MessageBox mb_IconInformation|mb_TopMost|mb_SetForeground "CAUTION: This is a private BETA version and will expire on Jan 20, 2014, 23:59. If you encounter a bug, malfunction or design flaw, please let us know by sending an e-mail to beta@mega.co.nz.$\r$\n$\r$\nIn this version, the scope of the sync engine is limited. Please bear in mind that:$\r$\n$\r$\n1. Deletions are only executed on the other side if they occur while the sync is live. Do not delete items from synced folders while this app is not running!$\r$\n2. Windows filenames are case insensitive. Do not place items a MEGA folder whose names would clash on the client. Loss of data would occur.$\r$\n3. Local filesystem items must not be exposed to the sync subsystem more than once. Any dupes, whether by nesting syncs or through filesystem links, will lead to unexpected results and loss of data.$\r$\n$\r$\nLimitiations in the current version that will be rectified in the future:$\r$\n$\r$\n1. No locking: Concurrent creation of identically named files and folders on different clients can result in server-side dupes and unexpected results.$\r$\n2. No in-place versioning: Deleted remote files can be found in the MEGA rubbish bin (SyncDebris folder), deleted local files in your computer's recycle bin.$\r$\n3. No delta writes: Changed files are always overwritten as a whole, which means that it is not a good idea to sync e.g. live database files.$\r$\n4. No direct peer-to-peer syncing: Even two machines in the same local subnet will still sync via the remote MEGA infrastructure.$\r$\n$\r$\nThank you for betatesting MEGAsync. We appreciate your pioneering spirit!"
  ;!insertmacro MUI_UNGETLANGUAGE
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Function GetPaths

  #Get DEFAULT VALUES
  System::Call 'shell32::SHGetSpecialFolderPath(i $HWNDPARENT, t .r1, i ${CSIDL_COMMON_APPDATA}, i0)i.r0'
  strCpy $ALL_USERS_INSTDIR $1

  System::Call "advapi32::GetUserName(t .r0, *i ${NSIS_MAX_STRLEN} r1) i.r2"
  strCpy $USERNAME $0
  System::Call 'shell32::SHGetSpecialFolderPath(i $HWNDPARENT, t .r1, i ${CSIDL_LOCALAPPDATA}, i0)i.r0'
  strCpy $CURRENT_USER_INSTDIR $1

  ClearErrors
  FileOpen $0 "$ALL_USERS_INSTDIR\megatmp.M1.txt" w
  IfErrors done
  FileWriteUTF16LE $0 "$CURRENT_USER_INSTDIR"
  FileClose $0
  FileOpen $0 "$ALL_USERS_INSTDIR\megatmp.M2.txt" w
  IfErrors done
  FileWriteUTF16LE $0 "$USERNAME"
  FileClose $0
done:
FunctionEnd

!macro Install3264DLL  source target
  ; If the dll already exists, rename it and try to delete it.
  ; This is to avoid issues with shared dlls loaded in another process
  ; (moving the dll does not break anything, and we can copy our new dll without issue).
  IfFileExists ${target} 0 new_install_${target}
    GetTempFileName $0
    Delete $0
    Rename ${target} $0
    !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED $0
  new_install_${target}:
    File "${source}"
    AccessControl::SetFileOwner ${target} "$USERNAME"
    AccessControl::GrantOnFile ${target} "$USERNAME" "GenericRead + GenericWrite"
!macroend

!ifndef BUILD_UNINSTALLER
Var CLEAN_OBSOLETE_DIR
Var CLEAN_LEFTOVERS
Var CLEAN_LAST_LEFTOVER

; Empty the directory passed in $R0: delete what is deletable, move locked-but-movable
; files (e.g. loaded exes/dlls) into $CLEAN_OBSOLETE_DIR under a unique name, and count
; in $CLEAN_LEFTOVERS the entries that can be neither deleted nor moved, including
; directories that cannot be listed ($CLEAN_LAST_LEFTOVER keeps the last such path for
; error reporting). Subdirectories are emptied recursively and removed once empty.
; Reparse points (directory junctions/symlinks) are never recursed into: only the link
; itself is removed, leaving its target untouched.
Function EmptyObsoleteDirectory
  Push $R1
  Push $R2
  Push $R3
  Push $R4
  ; Never enumerate through a reparse-point root: a junction/symlink passed as $R0
  ; would otherwise be walked into and its target emptied. Treat it as a leftover link
  ; (the caller removes the link itself; here we just avoid following it).
  System::Call 'kernel32::GetFileAttributesW(w "$R0")i.R4'
  IntCmp $R4 -1 empty_obsolete_rootok
  IntOp $R4 $R4 & 0x400
  IntCmp $R4 0 empty_obsolete_rootok empty_obsolete_rootok 0
    IntOp $CLEAN_LEFTOVERS $CLEAN_LEFTOVERS + 1
    StrCpy $CLEAN_LAST_LEFTOVER $R0
    Goto empty_obsolete_exit
  empty_obsolete_rootok:
  ClearErrors
  FindFirst $R1 $R2 "$R0\*"
  IfErrors 0 empty_obsolete_loop
    ; The directory cannot be listed (e.g. access denied): its content can be neither
    ; cleaned nor counted, so count the directory itself as a leftover. A listable
    ; directory always yields at least ".", so an error here means listing failed.
    ; The find handle is invalid on failure: exit without FindClose.
    IntOp $CLEAN_LEFTOVERS $CLEAN_LEFTOVERS + 1
    StrCpy $CLEAN_LAST_LEFTOVER $R0
    Goto empty_obsolete_exit
  empty_obsolete_loop:
    StrCmp $R2 "" empty_obsolete_done
    StrCmp $R2 "." empty_obsolete_next
    StrCmp $R2 ".." empty_obsolete_next
    StrCpy $R3 "$R0\$R2"
    System::Call 'kernel32::GetFileAttributesW(w "$R3")i.R4'
    IntCmp $R4 -1 empty_obsolete_file
    IntOp $R4 $R4 & 0x400
    IntCmp $R4 0 empty_obsolete_direntry empty_obsolete_direntry empty_obsolete_reparse
  empty_obsolete_direntry:
    IfFileExists "$R3\*.*" 0 empty_obsolete_file
      Push $R0
      StrCpy $R0 $R3
      Call EmptyObsoleteDirectory
      Pop $R0
      ; A failed removal is only reported, not counted: files still inside were already
      ; counted (or the directory was counted as unlistable), and an empty-but-locked
      ; directory is harmless to the new payload.
      ClearErrors
      RMDir "$R3"
      IfErrors 0 empty_obsolete_next
      DetailPrint "Could not remove directory: $R3"
      Goto empty_obsolete_next
  empty_obsolete_reparse:
    ; Junctions/symlinks are removed as links, never recursed into.
    ClearErrors
    RMDir "$R3"
    IfErrors 0 empty_obsolete_next
    ClearErrors
    Delete "$R3"
    IfErrors 0 empty_obsolete_next
    IntOp $CLEAN_LEFTOVERS $CLEAN_LEFTOVERS + 1
    StrCpy $CLEAN_LAST_LEFTOVER $R3
    Goto empty_obsolete_next
  empty_obsolete_file:
    ClearErrors
    Delete $R3
    IfErrors 0 empty_obsolete_next
    ; The file is locked. A loaded exe/dll cannot be deleted but can still be renamed,
    ; so move it out of the way into the obsolete directory.
    GetTempFileName $R4 "$CLEAN_OBSOLETE_DIR"
    Delete $R4
    ClearErrors
    Rename $R3 $R4
    IfErrors 0 empty_obsolete_next
    IntOp $CLEAN_LEFTOVERS $CLEAN_LEFTOVERS + 1
    StrCpy $CLEAN_LAST_LEFTOVER $R3
  empty_obsolete_next:
    FindNext $R1 $R2
    Goto empty_obsolete_loop
  empty_obsolete_done:
  FindClose $R1
  empty_obsolete_exit:
  Pop $R4
  Pop $R3
  Pop $R2
  Pop $R1
FunctionEnd

!endif

; Reparse-safe recursive delete of the tree in $R0: at every level a junction/symlink is
; removed as a link only, its target left untouched; locked entries are scheduled for
; deletion on reboot. Safe replacement for "RMDir /r /REBOOTOK" (NSIS RMDir /r recurses on
; FILE_ATTRIBUTE_DIRECTORY without checking FILE_ATTRIBUTE_REPARSE_POINT, so it follows
; junctions and deletes their target - dangerous for any tree under a user-writable parent
; such as the "MEGAsync.obsolete.*" sweep under %ProgramData%). Defined via a macro so the
; installer (RemoveTreeNoFollow) and the uninstaller (un.RemoveTreeNoFollow) share one
; implementation; UN prefixes the function name, UNL the labels (kept distinct so both
; instantiations can be compiled together without colliding).
!macro DEF_RemoveTreeNoFollow UN UNL
Function ${UN}RemoveTreeNoFollow
  Push $R1
  Push $R2
  Push $R3
  Push $R4

  ; If the root itself is a junction/symlink, remove only the link and stop.
  System::Call 'kernel32::GetFileAttributesW(w "$R0")i.R4'
  IntCmp $R4 -1 ${UNL}rtnf_exit ; invalid/gone: nothing to do
  IntOp $R4 $R4 & 0x400
  IntCmp $R4 0 ${UNL}rtnf_scan ${UNL}rtnf_scan ${UNL}rtnf_root_reparse
  ${UNL}rtnf_root_reparse:
    RMDir /REBOOTOK "$R0"
    Delete /REBOOTOK "$R0"
    Goto ${UNL}rtnf_exit

  ${UNL}rtnf_scan:
  ClearErrors
  FindFirst $R1 $R2 "$R0\*"
  IfErrors ${UNL}rtnf_exit
  ${UNL}rtnf_loop:
    StrCmp $R2 "" ${UNL}rtnf_done
    StrCmp $R2 "." ${UNL}rtnf_next
    StrCmp $R2 ".." ${UNL}rtnf_next
    StrCpy $R3 "$R0\$R2"
    System::Call 'kernel32::GetFileAttributesW(w "$R3")i.R4'
    IntCmp $R4 -1 ${UNL}rtnf_file
    IntOp $R4 $R4 & 0x400
    IntCmp $R4 0 ${UNL}rtnf_child_dir ${UNL}rtnf_child_dir ${UNL}rtnf_reparse
  ${UNL}rtnf_child_dir:
    IfFileExists "$R3\*.*" 0 ${UNL}rtnf_file
      Push $R0
      StrCpy $R0 $R3
      Call ${UN}RemoveTreeNoFollow
      Pop $R0
      RMDir /REBOOTOK "$R3" ; remove the now-empty subdir
      Goto ${UNL}rtnf_next
  ${UNL}rtnf_reparse:
    ; Junction/symlink: drop the link, never recurse into the target.
    RMDir /REBOOTOK "$R3"
    Delete /REBOOTOK "$R3"
    Goto ${UNL}rtnf_next
  ${UNL}rtnf_file:
    Delete /REBOOTOK "$R3"
  ${UNL}rtnf_next:
    FindNext $R1 $R2
    Goto ${UNL}rtnf_loop
  ${UNL}rtnf_done:
  FindClose $R1
  RMDir /REBOOTOK "$R0" ; remove the emptied root dir
  ${UNL}rtnf_exit:
  Pop $R4
  Pop $R3
  Pop $R2
  Pop $R1
FunctionEnd
!macroend

!ifndef BUILD_UNINSTALLER
!insertmacro DEF_RemoveTreeNoFollow "" ""
!endif
!insertmacro DEF_RemoveTreeNoFollow "un." "un_"

!macro CleanInstallDirectory
!ifndef BUILD_UNINSTALLER
  DetailPrint "Removing files from previous installation"
  StrCpy $INSTALL_REBOOT_PENDING "0"
  ; Release any lock on the install dir so it can be renamed/removed. SetOutPath only
  ; changes the working directory; every delete below stays rooted at the validated
  ; "...\MEGAsync" path, so $TEMP itself is never a deletion target.
  SetOutPath "$TEMP"

  ; Safety guard: $INSTDIR is derived from a value read at runtime, so before doing any
  ; recursive delete make sure it really points at our install folder (both the
  ; per-user and machine-wide paths end in "\MEGAsync"). Refuse to wipe anything else.
  StrCpy $R9 "$INSTDIR" "" -9
  StrCmp $R9 "\MEGAsync" clean_install_directory_start 0
    !insertmacro ExitWithError ${ERROR_PACKAGE_REJECTED} "Unexpected installation path. Aborting to avoid removing unrelated files."

  clean_install_directory_start:
  ; Sweep "MEGAsync.obsolete.*" directories left next to $INSTDIR by previous
  ; installations (they remain when files were locked and could only be scheduled
  ; for deletion after a reboot that never happened).
  StrLen $R5 "$INSTDIR"
  IntOp $R5 $R5 - 9
  StrCpy $R4 "$INSTDIR" $R5 ; parent directory of $INSTDIR (trailing "\MEGAsync" stripped)
  FindFirst $R3 $R2 "$R4\MEGAsync.obsolete.*"
  clean_obsolete_loop:
    StrCmp $R2 "" clean_obsolete_done
    ; Only touch entries whose real name starts with "MEGAsync.obsolete." (the find
    ; pattern can also match unrelated 8.3 short names).
    StrCpy $R1 $R2 18
    StrCmp $R1 "MEGAsync.obsolete." 0 clean_obsolete_next
    DetailPrint "Removing obsolete directory: $R4\$R2"
    ; Reparse-safe delete: $R4 is the (user-writable) parent of $INSTDIR, so an entry
    ; here may be an attacker-planted junction. Never follow it with RMDir /r.
    Push $R0
    StrCpy $R0 "$R4\$R2"
    Call RemoveTreeNoFollow
    Pop $R0
  clean_obsolete_next:
    FindNext $R3 $R2
    Goto clean_obsolete_loop
  clean_obsolete_done:
  FindClose $R3

  ; Nothing else to clean on a fresh install.
  IfFileExists "$INSTDIR\*.*" 0 clean_install_directory_done

  ; Retry a few times: handles held by the just-terminated app or the shell extension
  ; may take a moment to be released after taskkill. Move the old install directory
  ; away first so the new payload is installed into a clean $INSTDIR even if some old
  ; runtime DLLs can only be deleted after reboot. Use a sibling backup path so the
  ; rename remains on the same volume. Keep $R7 rooted at $INSTDIR before passing it
  ; to RMDir /r /REBOOTOK.
  StrCpy $R6 5
  clean_install_directory_retry:
    System::Call 'kernel32::GetTickCount()i.R8'
    StrCpy $R7 "$INSTDIR.obsolete.$R8.$R6"
    ; The error flag may still be set by earlier steps (shell extension unregister,
    ; temp file deletes), which would make a successful Rename look like a failure.
    ClearErrors
    Rename "$INSTDIR" "$R7"
    IfErrors 0 clean_install_directory_moved
    IntOp $R6 $R6 - 1
    IntCmp $R6 0 clean_install_directory_fallback clean_install_directory_fallback 0
    Sleep 1000
    Goto clean_install_directory_retry

  clean_install_directory_moved:
    Push $R0
    StrCpy $R0 "$R7"
    Call RemoveTreeNoFollow
    Pop $R0
    Goto clean_install_directory_done

  clean_install_directory_fallback:
    ; The whole-directory rename keeps failing: some process holds a handle without
    ; delete sharing below $INSTDIR (open console/Explorer handle, data file in use...).
    ; Fall back to per-file cleanup: delete what we can and move locked files out of
    ; the way so the new payload can still be installed into a clean directory.
    DetailPrint "Install directory is in use, removing its content file by file"
    StrCpy $CLEAN_OBSOLETE_DIR "$R7"
    CreateDirectory "$CLEAN_OBSOLETE_DIR"
    StrCpy $CLEAN_LEFTOVERS 0
    StrCpy $CLEAN_LAST_LEFTOVER ""
    Push $R0
    StrCpy $R0 "$INSTDIR"
    Call EmptyObsoleteDirectory
    Pop $R0
    Push $R0
    StrCpy $R0 "$CLEAN_OBSOLETE_DIR"
    Call RemoveTreeNoFollow
    Pop $R0
    IntCmp $CLEAN_LEFTOVERS 0 clean_install_directory_done clean_install_directory_done 0
    ; Some files could be neither deleted nor moved. At this point the old installation
    ; has already been partially removed, so aborting would leave the machine without a
    ; working install and nothing to roll back to. Proceed instead: the new payload is
    ; written with "SetOverwrite on", so each leftover is either overwritten by the
    ; matching new file or, if it does not belong to the new payload, simply left behind.
    DetailPrint "Warning: $CLEAN_LEFTOVERS item(s) from the previous installation are in use and could not be removed (last: $CLEAN_LAST_LEFTOVER). They will be overwritten by the new installation where needed."

  clean_install_directory_done:
  ClearErrors
  ; A /REBOOTOK deletion above may have scheduled locked leftovers (or a whole
  ; ".obsolete" directory) for removal on the next boot, raising the reboot flag. A
  ; later "SetRebootFlag false" in this section would silently discard that, so latch
  ; the requirement now; .onInstSuccess re-asserts it for the exit code and finish page.
  IfRebootFlag 0 clean_install_no_reboot_pending
    StrCpy $INSTALL_REBOOT_PENDING "1"
  clean_install_no_reboot_pending:
  SetOutPath "$INSTDIR"
!endif
!macroend

Section "Principal" SEC01
  !insertmacro DEBUG_MSG "Getting needed information"
  #Not sure why, if these lines does  not exist, the installation is blocked, even when they are repeated in GetPaths
  System::Call 'shell32::SHGetSpecialFolderPath(i $HWNDPARENT, t .r1, i ${CSIDL_COMMON_APPDATA}, i0)i.r0'
  strCpy $ALL_USERS_INSTDIR $1
  
  ${UAC.CallFunctionAsUser} GetPaths
readpaths:
  Sleep 1000

  FileOpen $R0 "$ALL_USERS_INSTDIR\megatmp.M1.txt" r
  IfErrors done
  FileReadUTF16LE $R0 "$CURRENT_USER_INSTDIR"
  FileOpen $R1 "$ALL_USERS_INSTDIR\megatmp.M2.txt" r
  IfErrors done
  FileReadUTF16LE $R1 "$USERNAME"
  IfErrors done
done:
  FileClose $R0
  FileClose $R1

  StrCmp $CURRENT_USER_INSTDIR "" readpaths 0
  StrCmp $USERNAME "" readpaths 0

  # Get registry uninstall strings (user process)
  ${UAC.CallFunctionAsUser} GetHKCUUninstallString
  # Get HKCU on elevated process (if needed)
  Call ReadHKCUUninstallString
  !insertmacro ReadHKLMUninstallString

  !insertmacro DEBUG_MSG "Checking install mode"
  
  Delete "$ALL_USERS_INSTDIR\megatmp.M1.txt"
  Delete "$ALL_USERS_INSTDIR\megatmp.M2.txt"
  ${If} ${Silent}
     ${If} $SILENT_MULTIUSER == "true"
        Goto alluser
     ${ElseIf} $SILENT_MULTIUSER == "false"
     ${OrIf} $SILENT_MULTIUSER == ""
        Goto currentuser
     ${Else}
        MessageBox MB_OK "Incorrect multiuser argument: true or false. Aborting"
        Abort
     ${EndIf}
  ${Else}
     StrCmp "${CURRENT_USER_INSTALLED_APP_MODE}" $MultiUser.InstallMode currentuser
  ${EndIf}
  
alluser:
  !insertmacro DEBUG_MSG "Install for all"
  SetShellVarContext all
  StrCpy $INSTDIR "$ALL_USERS_INSTDIR\MEGAsync"
  Call GetInstalledAppMode
  ${If} "$INSTALLED_APP_MODE" == "${CURRENT_USER_INSTALLED_APP_MODE}"
	!insertmacro ExitWithError ${ERROR_APPLICATION_ALREADY_EXISTS} "You already have an installation per user in your computer. Please uninstall and install it again."
  ${EndIf}
  goto modeselected
currentuser:
  !insertmacro DEBUG_MSG "Install for current user"
  SetShellVarContext current
  StrCpy $INSTDIR "$CURRENT_USER_INSTDIR\MEGAsync"
  Call GetInstalledAppMode
  ${If} "$INSTALLED_APP_MODE" == "${ALL_USERS_INSTALLED_APP_MODE}"
	!insertmacro ExitWithError ${ERROR_APPLICATION_ALREADY_EXISTS} "You already have a machine-wide installation in your computer. Please uninstall and install it again."
  ${EndIf}
modeselected:
  Call CheckDiskSpace
  !insertmacro DEBUG_MSG "Closing MEGAsync"
  ExecDos::exec /DETAILED /DISABLEFSR "$WINDIR\System32\taskkill.exe /f /t /IM MEGAsync.exe"
  ExecDos::exec /DETAILED /DISABLEFSR "$WINDIR\System32\taskkill.exe /f /t /IM MEGAupdater.exe"
  ExecDos::exec /DETAILED /DISABLEFSR "$WINDIR\System32\taskkill.exe /f /t /IM mega-desktop-app-gfxworker.exe"
  Sleep 1000

  !insertmacro DEBUG_MSG "Installing files"

  SetRebootFlag false
  SetOverwrite on

  ; Keep NSIS helper executables and temporary files out of the install directory.
  ; The cleanup below removes $INSTDIR recursively before the new payload is copied.
  SetOutPath "$TEMP"

; UnRegister shell extensions first
  !define LIBRARY_COM
  !define LIBRARY_SHELL_EXTENSION
  !define LIBRARY_IGNORE_VERSION

  IfFileExists "$INSTDIR\ShellExtX32.dll" 0 new_installation_x32
  DetailPrint "Uninstall old ShellExt 32"
  !insertmacro UnInstallLib REGDLL NOTSHARED REBOOT_NOTPROTECTED "$INSTDIR\ShellExtX32.dll"
  GetTempFileName $0
  Delete $0
  Rename "$INSTDIR\ShellExtX32.dll" $0
  Delete /REBOOTOK $0

  new_installation_x32:
  ${If} ${RunningX64}
    IfFileExists "$INSTDIR\ShellExtX64.dll" 0 new_installation_x64
    !define LIBRARY_X64
    DetailPrint "Uninstall old ShellExt 64"
    !insertmacro UnInstallLib REGDLL NOTSHARED REBOOT_NOTPROTECTED "$INSTDIR\ShellExtX64.dll"
    GetTempFileName $0
    Delete $0
    Rename "$INSTDIR\ShellExtX64.dll" $0
    Delete /REBOOTOK $0
    !undef LIBRARY_X64

    new_installation_x64:
  ${EndIf}

  !undef LIBRARY_COM
  !undef LIBRARY_SHELL_EXTENSION
  !undef LIBRARY_IGNORE_VERSION

  !insertmacro CleanInstallDirectory

!ifdef BUILD_X64_VERSION
    !insertmacro Install3264DLL "${VcRedist64Path}\vcruntime140.dll" "$INSTDIR\vcruntime140.dll"
    !insertmacro Install3264DLL "${VcRedist64Path}\vcruntime140_1.dll" "$INSTDIR\vcruntime140_1.dll"
    !insertmacro Install3264DLL "${VcRedist64Path}\msvcp140.dll" "$INSTDIR\msvcp140.dll"
    !insertmacro Install3264DLL "${VcRedist64Path}\msvcp140_1.dll" "$INSTDIR\msvcp140_1.dll"
    !insertmacro Install3264DLL "${VcRedist64Path}\msvcp140_2.dll" "$INSTDIR\msvcp140_2.dll"
    !insertmacro Install3264DLL "${VcRedist64Path}\msvcp140_atomic_wait.dll" "$INSTDIR\msvcp140_atomic_wait.dll"
    !insertmacro Install3264DLL "${VcRedist64Path}\msvcp140_codecvt_ids.dll" "$INSTDIR\msvcp140_codecvt_ids.dll"
    !insertmacro Install3264DLL "${VcRedist64Path}\concrt140.dll"  "$INSTDIR\concrt140.dll"
    !insertmacro Install3264DLL "${VcRedist64Path}\vccorlib140.dll" "$INSTDIR\vccorlib140.dll"
    !insertmacro Install3264DLL "${VcRedist64BasePath}\Microsoft.VC143.OpenMP\vcomp140.dll"  "$INSTDIR\vcomp140.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\ucrtbase.dll"  "$INSTDIR\ucrtbase.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-utility-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-utility-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-time-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-time-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-string-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-string-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-stdio-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-stdio-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-runtime-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-runtime-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-process-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-process-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-private-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-private-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-multibyte-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-multibyte-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-math-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-math-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-locale-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-locale-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-heap-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-heap-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-filesystem-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-filesystem-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-environment-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-environment-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-convert-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-convert-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-crt-conio-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-conio-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-util-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-util-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-timezone-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-timezone-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-sysinfo-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-sysinfo-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-synch-l1-2-0.dll"  "$INSTDIR\api-ms-win-core-synch-l1-2-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-synch-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-synch-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-string-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-string-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-rtlsupport-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-rtlsupport-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-profile-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-profile-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-processthreads-l1-1-1.dll"  "$INSTDIR\api-ms-win-core-processthreads-l1-1-1.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-processthreads-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-processthreads-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-processenvironment-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-processenvironment-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-namedpipe-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-namedpipe-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-memory-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-memory-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-localization-l1-2-0.dll"  "$INSTDIR\api-ms-win-core-localization-l1-2-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-libraryloader-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-libraryloader-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-interlocked-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-interlocked-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-heap-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-heap-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-handle-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-handle-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-file-l2-1-0.dll"  "$INSTDIR\api-ms-win-core-file-l2-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-file-l1-2-0.dll"  "$INSTDIR\api-ms-win-core-file-l1-2-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-file-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-file-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-errorhandling-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-errorhandling-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-debug-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-debug-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-datetime-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-datetime-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist64BasePath}\api-ms-win-core-console-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-console-l1-1-0.dll"
    !insertmacro Install3264DLL "${D3DRedist64BasePath}\d3dcompiler_47.dll"  "$INSTDIR\d3dcompiler_47.dll"
  !else
    !insertmacro Install3264DLL "${VcRedist32Path}\vcruntime140.dll" "$INSTDIR\vcruntime140.dll"
    !insertmacro Install3264DLL "${VcRedist32Path}\msvcp140.dll" "$INSTDIR\msvcp140.dll"
    !insertmacro Install3264DLL "${VcRedist32Path}\msvcp140_1.dll" "$INSTDIR\msvcp140_1.dll"
    !insertmacro Install3264DLL "${VcRedist32Path}\msvcp140_2.dll" "$INSTDIR\msvcp140_2.dll"
    !insertmacro Install3264DLL "${VcRedist32Path}\msvcp140_atomic_wait.dll" "$INSTDIR\msvcp140_atomic_wait.dll"
    !insertmacro Install3264DLL "${VcRedist32Path}\msvcp140_codecvt_ids.dll" "$INSTDIR\msvcp140_codecvt_ids.dll"
    !insertmacro Install3264DLL "${VcRedist32Path}\concrt140.dll"  "$INSTDIR\concrt140.dll"
    !insertmacro Install3264DLL "${VcRedist32Path}\vccorlib140.dll" "$INSTDIR\vccorlib140.dll"
    !insertmacro Install3264DLL "${VcRedist32BasePath}\Microsoft.VC143.OpenMP\vcomp140.dll"  "$INSTDIR\vcomp140.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\ucrtbase.dll"  "$INSTDIR\ucrtbase.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-utility-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-utility-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-time-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-time-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-string-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-string-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-stdio-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-stdio-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-runtime-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-runtime-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-process-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-process-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-private-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-private-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-multibyte-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-multibyte-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-math-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-math-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-locale-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-locale-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-heap-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-heap-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-filesystem-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-filesystem-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-environment-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-environment-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-convert-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-convert-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-crt-conio-l1-1-0.dll"  "$INSTDIR\api-ms-win-crt-conio-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-util-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-util-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-timezone-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-timezone-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-sysinfo-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-sysinfo-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-synch-l1-2-0.dll"  "$INSTDIR\api-ms-win-core-synch-l1-2-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-synch-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-synch-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-string-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-string-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-rtlsupport-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-rtlsupport-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-profile-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-profile-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-processthreads-l1-1-1.dll"  "$INSTDIR\api-ms-win-core-processthreads-l1-1-1.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-processthreads-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-processthreads-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-processenvironment-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-processenvironment-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-namedpipe-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-namedpipe-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-memory-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-memory-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-localization-l1-2-0.dll"  "$INSTDIR\api-ms-win-core-localization-l1-2-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-libraryloader-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-libraryloader-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-interlocked-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-interlocked-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-heap-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-heap-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-handle-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-handle-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-file-l2-1-0.dll"  "$INSTDIR\api-ms-win-core-file-l2-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-file-l1-2-0.dll"  "$INSTDIR\api-ms-win-core-file-l1-2-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-file-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-file-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-errorhandling-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-errorhandling-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-debug-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-debug-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-datetime-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-datetime-l1-1-0.dll"
    !insertmacro Install3264DLL "${WinRedist32BasePath}\api-ms-win-core-console-l1-1-0.dll"  "$INSTDIR\api-ms-win-core-console-l1-1-0.dll"
    !insertmacro Install3264DLL "${D3DRedist32BasePath}\d3dcompiler_47.dll"  "$INSTDIR\d3dcompiler_47.dll"
  !endif

!ifndef BUILD_UNINSTALLER  ; if building uninstaller, skip files below
  ;x86_32 files
  SetOutPath "$INSTDIR"
  File /r "${QT_DEPLOY_PATH}\*"
!endif

  ; Remove unused Qt libs
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\Qt5Xml.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\Qt5Concurrent.dll"

  ;Disable bearer plugin if it's a reinstallation
  RMDir /r "$INSTDIR\bearer"

  SetOutPath "$INSTDIR"
  SetOverwrite on
  AllowSkipFiles off
  File "${SRCDIR_MEGASYNC}\MEGAsync.exe"
  AccessControl::SetFileOwner "$INSTDIR\MEGAsync.exe" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\MEGAsync.exe" "$USERNAME" "GenericRead + GenericWrite"

  File "${SRCDIR_UPDATER}\MEGAupdater.exe"
  AccessControl::SetFileOwner "$INSTDIR\MEGAupdater.exe" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\MEGAupdater.exe" "$USERNAME" "GenericRead + GenericWrite"

  File "${SRCDIR_MEGASYNC}\mega-desktop-app-gfxworker.exe"
  AccessControl::SetFileOwner "$INSTDIR\mega-desktop-app-gfxworker.exe" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\mega-desktop-app-gfxworker.exe" "$USERNAME" "GenericRead + GenericWrite"

  File "installer\qt.conf"
  AccessControl::SetFileOwner "$INSTDIR\qt.conf" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\qt.conf" "$USERNAME" "GenericRead + GenericWrite"

  File "${SRCDIR_MEGASYNC}\Resources_common.rcc"
  AccessControl::SetFileOwner "$INSTDIR\Resources_common.rcc" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\Resources_common.rcc" "$USERNAME" "GenericRead + GenericWrite"

  File "${SRCDIR_MEGASYNC}\Resources_light.rcc"
  AccessControl::SetFileOwner "$INSTDIR\Resources_light.rcc" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\Resources_light.rcc" "$USERNAME" "GenericRead + GenericWrite"

  File "${SRCDIR_MEGASYNC}\Resources_dark.rcc"
  AccessControl::SetFileOwner "$INSTDIR\Resources_dark.rcc" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\Resources_dark.rcc" "$USERNAME" "GenericRead + GenericWrite"

  File "${SRCDIR_MEGASYNC}\Resources_qml.rcc"
  AccessControl::SetFileOwner "$INSTDIR\Resources_qml.rcc" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\Resources_qml.rcc" "$USERNAME" "GenericRead + GenericWrite"

  File "${SRCDIR_MEGASYNC}\qml.rcc"
  AccessControl::SetFileOwner "$INSTDIR\qml.rcc" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\qml.rcc" "$USERNAME" "GenericRead + GenericWrite"

  File "${SRCDIR_MEGASYNC}\avcodec-61.dll"
  AccessControl::SetFileOwner "$INSTDIR\avcodec-61.dll" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\avcodec-61.dll" "$USERNAME" "GenericRead + GenericWrite"

  File "${SRCDIR_MEGASYNC}\avformat-61.dll"
  AccessControl::SetFileOwner "$INSTDIR\avformat-61.dll" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\avformat-61.dll" "$USERNAME" "GenericRead + GenericWrite"

  File "${SRCDIR_MEGASYNC}\avutil-59.dll"
  AccessControl::SetFileOwner "$INSTDIR\avutil-59.dll" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\avutil-59.dll" "$USERNAME" "GenericRead + GenericWrite"

  File "${SRCDIR_MEGASYNC}\swscale-8.dll"
  AccessControl::SetFileOwner "$INSTDIR\swscale-8.dll" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\swscale-8.dll" "$USERNAME" "GenericRead + GenericWrite"

  File "${SRCDIR_MEGASYNC}\swresample-5.dll"
  AccessControl::SetFileOwner "$INSTDIR\swresample-5.dll" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\swresample-5.dll" "$USERNAME" "GenericRead + GenericWrite"



  !insertmacro DEBUG_MSG "Registering DLLs"

  !define LIBRARY_COM
  !define LIBRARY_SHELL_EXTENSION
  !define LIBRARY_IGNORE_VERSION

  ${If} ${RunningX64}
    !define LIBRARY_X64
    DetailPrint "Install ShellExt 64"
    File "/oname=$INSTDIR\ShellExtX64.msix" "${SRCDIR_MEGASHELLEXT_X64}\MEGAShellExt.msix"
    AccessControl::SetFileOwner "$INSTDIR\ShellExtX64.msix" "$USERNAME"
    AccessControl::GrantOnFile "$INSTDIR\ShellExtX64.msix" "$USERNAME" "GenericRead + GenericWrite"
    !insertmacro InstallLib REGDLL NOTSHARED NOREBOOT_NOTPROTECTED "${SRCDIR_MEGASHELLEXT_X64}\MEGAShellExt.dll" "$INSTDIR\ShellExtX64.dll" "$INSTDIR"
    ${If} ${Errors}
        DetailPrint "Install ShellExt 64 failed"
        ClearErrors
    ${endIf}
    AccessControl::SetFileOwner "$INSTDIR\ShellExtX64.dll" "$USERNAME"
    AccessControl::GrantOnFile "$INSTDIR\ShellExtX64.dll" "$USERNAME" "GenericRead + GenericWrite"
    !undef LIBRARY_X64
!ifndef BUILD_X64_VERSION
    File "/oname=$INSTDIR\ShellExtX32.dll" "${SRCDIR_MEGASHELLEXT_X32}\MEGAShellExt.dll"
    AccessControl::SetFileOwner "$INSTDIR\ShellExtX32.dll" "$USERNAME"
    AccessControl::GrantOnFile "$INSTDIR\ShellExtX32.dll" "$USERNAME" "GenericRead + GenericWrite"
  ${Else}
    DetailPrint "Install ShellExt 32"
    !insertmacro InstallLib REGDLL NOTSHARED NOREBOOT_NOTPROTECTED "${SRCDIR_MEGASHELLEXT_X32}\MEGAShellExt.dll" "$INSTDIR\ShellExtX32.dll" "$INSTDIR"
    ${If} ${Errors}
        DetailPrint "Install ShellExt 32 failed"
        ClearErrors
    ${endIf}
    AccessControl::SetFileOwner "$INSTDIR\ShellExtX32.dll" "$USERNAME"
    AccessControl::GrantOnFile "$INSTDIR\ShellExtX32.dll" "$USERNAME" "GenericRead + GenericWrite"
!endif
  ${EndIf}

  !undef LIBRARY_COM
  !undef LIBRARY_SHELL_EXTENSION
  !undef LIBRARY_IGNORE_VERSION

!ifndef BUILD_UNINSTALLER  ; if building uninstaller, skip this check
  File "${SRCDIR_MEGASYNC}\${UNINSTALLER_NAME}"
  AccessControl::SetFileOwner "$INSTDIR\${UNINSTALLER_NAME}" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\${UNINSTALLER_NAME}" "$USERNAME" "GenericRead + GenericWrite"
!endif

#  !insertmacro DEBUG_MSG "Adding firewall rule"
#  liteFirewall::RemoveRule "$INSTDIR\MEGAsync.exe" "MEGAsync"
#  Pop $0
#  liteFirewall::AddRule "$INSTDIR\MEGAsync.exe" "MEGAsync"
#  Pop $0

  !insertmacro DEBUG_MSG "Creating shortcuts"
  SetRebootFlag false
  StrCmp "CurrentUser" $MultiUser.InstallMode currentuser2
  SetShellVarContext all
  Call CreateShortCuts ; Call with elevation just in case it is an all users installation
  Goto MegaShortcutsCreated
currentuser2:
  SetShellVarContext current
  ${UAC.CallFunctionAsUser} CreateShortCuts
MegaShortcutsCreated:
SectionEnd

Function CheckDiskSpace
  SectionGetSize ${SEC01} $0
  IntOp $0 $0 + 10240

  ${GetRoot} "$INSTDIR" $1
  ${DriveSpace} "$1" "/D=F /S=K" $2

  ${If} $2 == ""
    Return
  ${EndIf}

  IntCmpU $2 $0 enough_space disk_full enough_space

disk_full:
  !insertmacro ExitWithError ${ERROR_DISK_FULL} "There is not enough disk space available to install MEGA Desktop App."

enough_space:
FunctionEnd

Section -AdditionalIcons

SectionEnd

Function WriteOnLocalMachineReg
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_LOCAL_MACHINE} "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\MEGAsync.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_LOCAL_MACHINE} "${PRODUCT_UNINST_KEY}" "DisplayName" "${PRODUCT_NAME}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_LOCAL_MACHINE} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_LOCAL_MACHINE} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\${UNINSTALLER_NAME}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_LOCAL_MACHINE} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\MEGAsync.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_LOCAL_MACHINE} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_LOCAL_MACHINE} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_LOCAL_MACHINE} "${PRODUCT_UNINST_KEY}" "${PRODUCT_STARTMENU_REGVAL}" "$ICONS_GROUP"
FunctionEnd

Function WriteOnCurrentUserReg
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\MEGAsync.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_UNINST_KEY}" "DisplayName" "${PRODUCT_NAME}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\${UNINSTALLER_NAME}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\MEGAsync.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_UNINST_KEY}" "${PRODUCT_STARTMENU_REGVAL}" "$ICONS_GROUP"
FunctionEnd

Section -Post
  ;First remove the HKLM as it may contain old info from old installers 
  !insertmacro CheckHKLMUninstallInfo
  StrCmp "CurrentUser" $MultiUser.InstallMode currentuser

  ;Called if we are installing the app for all the users
  Call WriteOnLocalMachineReg
  Goto continuePost
currentuser:
  ${UAC.CallFunctionAsUser} WriteOnCurrentUserReg
continuePost:
  AccessControl::SetFileOwner "$INSTDIR\MEGA Website.url" "$USERNAME"
  AccessControl::GrantOnFile "$INSTDIR\MEGA Website.url" "$USERNAME" "GenericRead + GenericWrite"

  Delete "$INSTDIR\NSIS.Library.RegTool*.exe"
SectionEnd

Function un.onInit

  ${GetParameters} $R0
  ClearErrors
  ${GetOptions} $R0 "/cleanup" $0
  ${IfNot} ${Errors}
    StrCpy $0 0
cleanup_wait:
    Sleep 1000
    ClearErrors
    Delete "$INSTDIR\${UNINSTALLER_NAME}"
    IfErrors cleanup_retry cleanup_done
cleanup_retry:
    IntOp $0 $0 + 1
    IntCmp $0 10 cleanup_done cleanup_wait cleanup_wait
cleanup_done:
    RMDir /r "$INSTDIR"
    Quit
  ${EndIf}
  !insertmacro MULTIUSER_UNINIT
  StrCpy $APP_NAME "${PRODUCT_NAME}"
  !insertmacro CheckUserToRunElevated
  !insertmacro MUI_UNGETLANGUAGE

FunctionEnd

Function un.UninstallSyncs
  ExecDos::exec "$INSTDIR\MEGAsync.exe /uninstall"
FunctionEnd

Function un.RemoveCurrentUserReg
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_DIR_REGKEY}"
FunctionEnd

Function un.RemoveCommonCurrentUserReg
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_DIR_USER_REGKEY}"
  DeleteRegKey /ifempty ${PRODUCT_UNINST_ROOT_KEY_CURRENT_USER} "${PRODUCT_DIR_PUBLISHER_REGPATH}"
 FunctionEnd
 
Section Uninstall
  ExecDos::exec /DETAILED /DISABLEFSR "$WINDIR\System32\taskkill.exe /f /t /IM MEGASync.exe"
  
  Sleep 1000
  
  ${UAC.CallFunctionAsUser} un.UninstallSyncs
  Sleep 1000

  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  Delete "$INSTDIR\${PRODUCT_NAME}.url"

  ;Shell extension(s)
  !define LIBRARY_COM
  !define LIBRARY_SHELL_EXTENSION
  !insertmacro UnInstallLib REGDLL NOTSHARED REBOOT_NOTPROTECTED "$INSTDIR\ShellExtX32.dll"
  ${If} ${RunningX64}
    !define LIBRARY_X64
    !insertmacro UnInstallLib REGDLL NOTSHARED REBOOT_NOTPROTECTED "$INSTDIR\ShellExtX64.dll"
    !undef LIBRARY_X64
  ${EndIf}
  !undef LIBRARY_COM
  !undef LIBRARY_SHELL_EXTENSION
  Delete "$INSTDIR\ShellExtX64.msix"
  Delete "$INSTDIR\ShellExtX32.msix"

  ;QT4 files
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\QtNetwork4.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\QtGui4.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\QtCore4.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\QtSvg4.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\QtXml4.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qgif4.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qico4.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qjpeg4.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qmng4.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qsvg4.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qtga4.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qtiff4.dll"

  ;QT5 files
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\Qt5Core.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\Qt5Gui.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\Qt5Widgets.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\Qt5Network.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\Qt5Xml.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\Qt5Svg.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\Qt5Concurrent.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\icudt53.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\icuin53.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\icuuc53.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\icudt54.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\icuin54.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\icuuc54.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qdds.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qgif.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qicns.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qico.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qjp2.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qjpeg.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qmng.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qsvg.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qtga.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qtiff.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qwbmp.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\imageformats\qwebp.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\accessible\qtaccessiblecompatwidgets4.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\accessible\qtaccessiblewidgets4.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\iconengines\qsvgicon.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\platforms\qwindows.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\styles\qwindowsvistastyle.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\bearer\qgenericbearer.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\bearer\qnativewifibearer.dll"
  Delete "$INSTDIR\leftbanner\*"

  ;VC++ Redistributable
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\vcruntime140_1.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\msvcp140.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\msvcp140_1.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\msvcp140_2.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\msvcp140_codecvt_ids.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\msvcp140_atomic_wait.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\concrt140.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\vccorlib140.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\vcomp140.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\vcruntime140.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\ucrtbase.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-utility-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-time-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-string-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-stdio-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-runtime-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-process-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-private-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-multibyte-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-math-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-locale-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-heap-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-filesystem-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-environment-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-convert-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-crt-conio-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-core-util-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-core-timezone-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-core-sysinfo-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-core-synch-l1-2-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED  "$INSTDIR\api-ms-win-core-synch-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-string-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-rtlsupport-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-profile-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-processthreads-l1-1-1.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-processthreads-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-processenvironment-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-namedpipe-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-memory-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-localization-l1-2-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-libraryloader-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-interlocked-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-heap-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-handle-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-file-l2-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-file-l1-2-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-file-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-errorhandling-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-debug-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-datetime-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\api-ms-win-core-console-l1-1-0.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\d3dcompiler_47.dll"

  ;Common files
  Delete "$INSTDIR\MEGAsync.exe"
  Delete "$INSTDIR\MEGAupdater.exe"
  Delete "$INSTDIR\mega-desktop-app-gfxworker.exe"

  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\libeay32.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\ssleay32.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\libcurl.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\cares.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\libuv.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\qt.conf"
  Delete "$INSTDIR\Resources_common.rcc"
  Delete "$INSTDIR\Resources_macx.rcc"
  Delete "$INSTDIR\Resources_linux.rcc"
  Delete "$INSTDIR\Resources_win.rcc"
  Delete "$INSTDIR\Resources_light.rcc"
  Delete "$INSTDIR\Resources_dark.rcc"
  Delete "$INSTDIR\Resources_qml.rcc"
  Delete "$INSTDIR\qml.rcc"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\NSIS.Library.RegTool*.exe"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\avcodec-59.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\avformat-59.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\avutil-57.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\swscale-6.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\swresample-4.dll"

  ;Still remove old DLLs though we no longer produce them (non-VCPKG may still produce them)
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\avcodec-57.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\avformat-57.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\avutil-55.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\swscale-4.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\swresample-2.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\libsodium.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\pdfium.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\libcrypto-1_1-x64.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\libssl-1_1-x64.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\libcrypto-1_1.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\libssl-1_1.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\libssl-3-x64.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\libcrypto-3-x64.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\libssl-3.dll"
  !insertmacro UnInstallLib DLL SHARED REBOOT_NOTPROTECTED "$INSTDIR\libcrypto-3.dll"

  !insertmacro GetUninstalledAppMode
  !insertmacro CheckHKLMUninstallInfo
  
  ${UAC.CallFunctionAsUser} un.GetStartMenuPage

  StrCmp "${CURRENT_USER_INSTALLED_APP_MODE}" "$INSTALLED_APP_MODE" currentuserRemoving

  ;Run if we have a machine-wide app installed
  SetShellVarContext all
  !insertmacro RemoveLocalMachineReg
  Call un.RemoveMegaShortcuts
  Goto continueRemoving
currentuserRemoving:
  SetShellVarContext current
  ${UAC.CallFunctionAsUser} un.RemoveMegaShortcuts
  ${UAC.CallFunctionAsUser} un.RemoveCurrentUserReg
continueRemoving:
  ${UAC.CallFunctionAsUser} un.RemoveCommonCurrentUserReg
  
  ; Sweep any "MEGAsync.obsolete.*" directories a previous install's cleanup left next to
  ; $INSTDIR (they persist when a reboot-deferred deletion never happened). Reparse-safe so
  ; a junction planted under the (possibly user-writable) parent is never followed.
  StrCpy $R9 "$INSTDIR" "" -9
  StrCmp $R9 "\MEGAsync" 0 un_obsolete_sweep_done
    StrLen $R5 "$INSTDIR"
    IntOp $R5 $R5 - 9
    StrCpy $R4 "$INSTDIR" $R5 ; parent directory of $INSTDIR (trailing "\MEGAsync" stripped)
    FindFirst $R3 $R2 "$R4\MEGAsync.obsolete.*"
    un_obsolete_sweep_loop:
      StrCmp $R2 "" un_obsolete_sweep_close
      StrCpy $R1 $R2 18
      StrCmp $R1 "MEGAsync.obsolete." 0 un_obsolete_sweep_next
      DetailPrint "Removing obsolete directory: $R4\$R2"
      Push $R0
      StrCpy $R0 "$R4\$R2"
      Call un.RemoveTreeNoFollow
      Pop $R0
    un_obsolete_sweep_next:
      FindNext $R3 $R2
      Goto un_obsolete_sweep_loop
    un_obsolete_sweep_close:
    FindClose $R3
  un_obsolete_sweep_done:

  ; Try to remove what is possible from the main uninstaller process
  RMDir /r "$INSTDIR"

  ; Run a temporary copy only for the final cleanup once this process exits
  InitPluginsDir
  CopyFiles /SILENT "$EXEPATH" "$PluginsDir\${UNINSTALLER_NAME}"
  Exec '"$PluginsDir\${UNINSTALLER_NAME}" /cleanup _?=$INSTDIR'

  SetAutoClose true
  SetRebootFlag false
SectionEnd
