#include "AppStatsEvents.h"

// Deprecated are not displayed
QHash<AppStatsEvents::EventTypes, const char*> AppStatsEvents::statsMap = {
    { AppStatsEvents::EVENT_1ST_START, "MEGAsync first start" },
    { AppStatsEvents::EVENT_1ST_SYNC, "MEGAsync first sync" },
    { AppStatsEvents::EVENT_1ST_SYNCED_FILE, "MEGAsync first synced file" },
    { AppStatsEvents::EVENT_1ST_WEBCLIENT_DL, "MEGAsync first webclient download" },
    { AppStatsEvents::EVENT_UNINSTALL_STATS, "{\"it\":%1,\"act\":%2,\"lt\":%3}" },
    { AppStatsEvents::EVENT_ACC_CREATION_START, "MEGAsync account creation start" },
    { AppStatsEvents::EVENT_PRO_REDIRECT, "Redirection to PRO" },
    { AppStatsEvents::EVENT_MEM_USAGE, "%1 %2 %3"},
    { AppStatsEvents::EVENT_UPDATE, "MEGAsync update" },
    { AppStatsEvents::EVENT_UPDATE_OK, "MEGAsync updated OK" },
    { AppStatsEvents::EVENT_DUP_FINISHED_TRSF, "Duplicated finished transfer: %1" },
    { AppStatsEvents::EVENT_OVER_STORAGE_DIAL, "Overstorage dialog shown" },
    { AppStatsEvents::EVENT_OVER_STORAGE_NOTIF, "Overstorage notification shown" },
    { AppStatsEvents::EVENT_OVER_STORAGE_MSG, "Overstorage warning shown" },
    { AppStatsEvents::EVENT_ALMOST_OVER_STORAGE_MSG, "Almost overstorage warning shown" },
    { AppStatsEvents::EVENT_ALMOST_OVER_STORAGE_NOTIF, "Almost overstorage notification shown" },
    { AppStatsEvents::EVENT_MAIN_DIAL_WHILE_OVER_QUOTA, "Main dialog shown while overquota" },
    { AppStatsEvents::EVENT_MAIN_DIAL_WHILE_ALMOST_OVER_QUOTA, "Main dialog shown while almost overquota" },
    { AppStatsEvents::EVENT_RED_LIGHT_USED_STORAGE_MISMATCH, "Red light does not match used storage" },
    { AppStatsEvents::EVENT_TRSF_OVER_QUOTA_DIAL, "Transfer over quota dialog shown" },
    { AppStatsEvents::EVENT_TRSF_OVER_QUOTA_NOTIF, "Transfer over quota os notification shown" },
    { AppStatsEvents::EVENT_TRSF_OVER_QUOTA_MSG, "Transfer over quota ui message shown" },
    { AppStatsEvents::EVENT_TRSF_ALMOST_OVER_QUOTA_MSG, "Transfer almost over quota ui message shown" },
    { AppStatsEvents::EVENT_PAYWALL_NOTIF, "Paywall notification shown" },
    { AppStatsEvents::EVENT_SYNC_ADD_FAIL_API_EACCESS, "Sync addition fails with API_EACCESS" },
    { AppStatsEvents::EVENT_TRSF_ALMOST_OVERQUOTA_NOTIF, "Transfer almost over quota os notification shown" },
    { AppStatsEvents::EVENT_1ST_BACKUP, "MEGAsync first backup" },
    { AppStatsEvents::EVENT_1ST_BACKED_UP_FILE, "MEGAsync first backed-up file" },
    { AppStatsEvents::EVENT_SI_NAMECONFLICT_SOLVED_MANUALLY, "Name conflict issue solved manually" },
    { AppStatsEvents::EVENT_SI_NAMECONFLICT_SOLVED_AUTOMATICALLY, "Name conflict issue solved automatically" },
    { AppStatsEvents::EVENT_SI_NAMECONFLICT_SOLVED_SEMI_AUTOMATICALLY, "Name conflict issue solved semi-automatically" },
    { AppStatsEvents::EVENT_SI_LOCALREMOTE_SOLVED_MANUALLY, "Local/Remote issue solved manually" },
    { AppStatsEvents::EVENT_SI_LOCALREMOTE_SOLVED_AUTOMATICALLY, "Local/Remote issue solved automatically" },
    { AppStatsEvents::EVENT_SI_LOCALREMOTE_SOLVED_SEMI_AUTOMATICALLY, "Local/Remote issue solved semi-automatically" },
    { AppStatsEvents::EVENT_SI_IGNORE_SOLVED_MANUALLY, "Issue ignored manually" },
    { AppStatsEvents::EVENT_SI_STALLED_ISSUE_RECEIVED, "Stalled issue received: Type %1" },
    { AppStatsEvents::EVENT_SI_IGNORE_ALL_SYMLINK, "All symlink ignored" },
    { AppStatsEvents::EVENT_SI_SMART_MODE_FIRST_SELECTED, "Smart mode selected by default" },
    { AppStatsEvents::EVENT_SI_ADVANCED_MODE_FIRST_SELECTED, "Advanced mode selected by default" },
    { AppStatsEvents::EVENT_SI_CHANGE_TO_SMART_MODE, "Smart mode selected" },
    { AppStatsEvents::EVENT_SI_CHANGE_TO_ADVANCED_MODE, "Advanced mode selected" },
    { AppStatsEvents::EVENT_SI_FINGERPRINT_MISSING_SOLVED_MANUALLY, "Cloud fingerprint missing solved manually" },
    { AppStatsEvents::EVENT_DAILY_ACTIVE_USER, "Daily Active Users (DAU) - acctype: %1" },
    { AppStatsEvents::EVENT_MONTHLY_ACTIVE_USER, "Monthly Active Users (MAU) - acctype: %1" },
    { AppStatsEvents::EVENT_LOGIN_CLICKED, "Log in clicked" },
    { AppStatsEvents::EVENT_LOGOUT_CLICKED, "Log out clicked" },
    { AppStatsEvents::EVENT_TRANSFER_TAB_CLICKED, "Transfer tab clicked" },
    { AppStatsEvents::EVENT_NOTIFICATION_TAB_CLICKED, "Notification tab clicked" },
    { AppStatsEvents::EVENT_NOTIFICATION_SETTINGS_CLICKED, "Show notification settings clicked" },
    { AppStatsEvents::EVENT_UPGRADE_ACCOUNT_CLICKED, "Upgrade account clicked" },
    { AppStatsEvents::EVENT_OPEN_TRANSFER_MANAGER_CLICKED, "Open transfer manager clicked" },
    { AppStatsEvents::EVENT_ADD_SYNC_CLICKED, "Add sync clicked" },
    { AppStatsEvents::EVENT_ADD_BACKUP_CLICKED, "Add backup clicked" },
    { AppStatsEvents::EVENT_UPLOAD_CLICKED, "Upload clicked" },
    { AppStatsEvents::EVENT_AVATAR_CLICKED, "Settings clicked (avatar)" },
    { AppStatsEvents::EVENT_MENU_CLICKED, "Show options clicked" },
    { AppStatsEvents::EVENT_MENU_ABOUT_CLICKED, "About clicked (menu)" },
    { AppStatsEvents::EVENT_MENU_CLOUD_DRIVE_CLICKED, "Cloud drive clicked (menu)" },
    { AppStatsEvents::EVENT_MENU_ADD_SYNC_CLICKED, "Add sync clicked (menu)" },
    { AppStatsEvents::EVENT_MENU_ADD_BACKUP_CLICKED, "Add backup clicked (menu)" },
    { AppStatsEvents::EVENT_MENU_OPEN_LINKS_CLICKED, "Open links clicked (menu)" },
    { AppStatsEvents::EVENT_MENU_UPLOAD_CLICKED, "Upload clicked (menu)" },
    { AppStatsEvents::EVENT_MENU_DOWNLOAD_CLICKED, "Download clicked (menu)" },
    { AppStatsEvents::EVENT_MENU_STREAM_CLICKED, "Stream clicked (menu)" },
    { AppStatsEvents::EVENT_MENU_SETTINGS_CLICKED, "Settings clicked (menu)" },
    { AppStatsEvents::EVENT_MENU_EXIT_CLICKED, "Exit clicked (menu)" },
    { AppStatsEvents::EVENT_SETTINGS_GENERAL_TAB_CLICKED, "Settings general tab clicked" },
    { AppStatsEvents::EVENT_SETTINGS_ACCOUNT_TAB_CLICKED, "Settings account tab clicked" },
    { AppStatsEvents::EVENT_SETTINGS_SYNC_TAB_CLICKED, "Settings sync tab clicked" },
    { AppStatsEvents::EVENT_SETTINGS_BACKUP_TAB_CLICKED, "Settings backup tab clicked" },
    { AppStatsEvents::EVENT_SETTINGS_SECURITY_TAB_CLICKED, "Settings security tab clicked" },
    { AppStatsEvents::EVENT_SETTINGS_FOLDERS_TAB_CLICKED, "Settings folders tab clicked" },
    { AppStatsEvents::EVENT_SETTINGS_NETWORK_TAB_CLICKED, "Settings network tab clicked" },
    { AppStatsEvents::EVENT_SETTINGS_NOTIFICATIONS_TAB_CLICKED, "Settings notifications tab clicked" },
    { AppStatsEvents::EVENT_SETTINGS_EXPORT_KEY_CLICKED, "Settings export key clicked" },
    { AppStatsEvents::EVENT_SETTINGS_CHANGE_PASSWORD_CLICKED, "Settings change password clicked" },
    { AppStatsEvents::EVENT_SETTINGS_REPORT_ISSUE_CLICKED, "Settings report issue clicked" }
};

const char* AppStatsEvents::getEventMessage(EventTypes event)
{
    if (!statsMap.contains(event))
    {
        return "";
    }

    return statsMap[event];
}
