
set(DESKTOP_APP_CONTROL_HEADERS
    control/AccountStatusController.h
    control/AppStatsEvents.h
    control/ConnectivityChecker.h
    control/CrashHandler.h
    control/DialogOpener.h
    control/DownloadQueueController.h
    control/EmailRequester.h
    control/ExportProcessor.h
    control/FileFolderAttributes.h
    control/HTTPServer.h
    control/LinkProcessor.h
    control/LoginController.h
    control/MegaDownloader.h
    control/MegaSyncLogger.h
    control/MegaUploader.h
    control/TextDecorator.h
    control/ThreadPool.h
    control/TransferBatch.h
    control/TransferRemainingTime.h
    control/UpdateTask.h
    control/UserAttributesManager.h
    control/Utilities.h
    control/Version.h
    control/gzjoin.h
    control/qrcodegen.h
    control/Preferences/EncryptedSettings.h
    control/Preferences/EphemeralCredentials.h
    control/Preferences/Preferences.h
)

set(DESKTOP_APP_CONTROL_SOURCES
    control/AccountStatusController.cpp
    control/ConnectivityChecker.cpp
    control/CrashHandler.cpp
    control/DialogOpener.cpp
    control/DownloadQueueController.cpp
    control/EmailRequester.cpp
    control/ExportProcessor.cpp
    control/FileFolderAttributes.cpp
    control/HTTPServer.cpp
    control/LinkProcessor.cpp
    control/LoginController.cpp
    control/MegaDownloader.cpp
    control/MegaSyncLogger.cpp
    control/MegaUploader.cpp
    control/TextDecorator.cpp
    control/ThreadPool.cpp
    control/TransferBatch.cpp
    control/TransferRemainingTime.cpp
    control/UpdateTask.cpp
    control/UserAttributesManager.cpp
    control/Utilities.cpp
    control/qrcodegen.c
    control/Preferences/EncryptedSettings.cpp
    control/Preferences/EphemeralCredentials.cpp
    control/Preferences/Preferences.cpp
)

target_sources(MEGAsync
    PRIVATE
    ${DESKTOP_APP_CONTROL_HEADERS}
    ${DESKTOP_APP_CONTROL_SOURCES}
)

target_include_directories(MEGAsync PRIVATE ${CMAKE_CURRENT_LIST_DIR})
