#ifndef NOTIFICATION_ALERT_TYPES_H
#define NOTIFICATION_ALERT_TYPES_H

enum class AlertType
{
    UNKNOWN = 0,
    ALL,
    CONTACTS,
    SHARES,
    PAYMENTS,
    TAKEDOWNS
};

#endif // NOTIFICATION_ALERT_TYPES_H
