pragma Singleton
import QtQuick 2.15

QtObject {
    id: root

    readonly property string addExclusions: qsTr("Add Exclusions")
    readonly property string manageExclusionsDescription: qsTr("Here you can exclude files and folders from being synced with your cloud drive. This can be useful for large files, files that you don't need on all of your devices,or certain file types that need not be synced.")
    readonly property string manageExclusions: qsTr("Manage exclusions")
    readonly property string nameRulesDescription: qsTr("Choose which files or folders you want to exclude from")
    readonly property string value: qsTr("Value")
    readonly property string sizeRulesTitle: qsTr("Exclude files by size")
    readonly property string sizeRule: qsTr("Exclude file sizes")
    readonly property string sizeRuleDescription: qsTr("Exclude files by specifying the lower and upper size limit, or just the files that are greater than or lesser than a specific size.")
    readonly property string done: qsTr("Done")
    readonly property string addExclusionDescription: qsTr("Choose if you want to exclude a file or a folder. You can exclude specific file types or a file/folder that starts, ends, contains, or equals a name (or part of a name).")
    readonly property string addExclusion: qsTr("Add Exclusion")
    readonly property string editExclusion: qsTr("Edit Exclusion")
    readonly property string dropDownsTitle: qsTr("You will exclude:")
    readonly property string files: qsTr("Files")
    readonly property string folders: qsTr("Folders")
    readonly property string extensions: qsTr("Extensions")
    readonly property string beginningWith: qsTr("Beginning with")
    readonly property string containing: qsTr("Containing")
    readonly property string endingWith: qsTr("Ending")
    readonly property string equalTo: qsTr("Equal to")
    readonly property string cancel: qsTr("Cancel")
    readonly property string filesBeginningWith: qsTr("Files beginning with:")
    readonly property string rulePlaceholder: qsTr("Use comma (“,”) to separate multiple items")
    readonly property string byteUnit: QT_TRANSLATE_NOOP("Sizes", "B")
    readonly property string kiloByte: QT_TRANSLATE_NOOP("Sizes", "KB")
    readonly property string megaByte: QT_TRANSLATE_NOOP("Sizes", "MB")
    readonly property string gigaByte: QT_TRANSLATE_NOOP("Sizes", "GB")
    readonly property string outsideOf: qsTr("Outside of")
    readonly property string biggerThan: qsTr("Bigger than")
    readonly property string smallerThan: qsTr("Smaller than")
    readonly property string and: qsTr("and")
    readonly property string excludeByName: qsTr("Exclude by name")
    readonly property string restoreDefaults: qsTr("Restore defaults")
    readonly property string typeHeader: qsTr("type")
    readonly property string propertyHeader: qsTr("property")
    readonly property string valueHeader: qsTr("value")
    readonly property string removeConfirmationTitle: qsTr("Remove this exclusion?")
    readonly property string removeFilesBeginning: qsTr("Files beginning with “%1” will be included on this sync.")
    readonly property string removeFoldersBeginning: qsTr("Folders beginning with “%1” will be included on this sync.")
    readonly property string removeFilesContaining: qsTr("Files containing “%1” will be included on this sync.")
    readonly property string removeFoldersContaining: qsTr("Folders containing “%1” will be included on this sync.")
    readonly property string removeFilesEnding: qsTr("Files ending with “%1” will be included on this sync.")
    readonly property string removeFoldersEnding: qsTr("Folders ending with “%1” will be included on this sync.")
    readonly property string removeFilesEqual: qsTr("Files equal to “%1” will be included on this sync.")
    readonly property string removeFoldersEqual: qsTr("Folders equal to “%1” will be included on this sync.")
    readonly property string removeExtension: qsTr("Files with this extension “%1” will be included")
    readonly property string removeButon: qsTr("Remove")
    readonly property string askAgainText: qsTr("Don’t ask me again")
    readonly property string hintText: qsTr("Set a minimum and maximum value for file sizes. Files outside this range will be excluded.")
}
