pragma Singleton
import QtQuick 2.12

QtObject {

    // Sorted alphabetically

    readonly property var accountTypeFree: qsTr("Free")
    readonly property var accountTypeProI: qsTr("Pro I")
    readonly property var accountTypeProII: qsTr("Pro II")
    readonly property var accountTypeProIII: qsTr("Pro III")
    readonly property var accountTypeLite: qsTr("Pro Lite")
    readonly property var accountTypeBusiness: qsTr("Business")
    readonly property var accountTypeProFlexi: qsTr("Pro Flexi")
    readonly property var addFolders: qsTr("Add folders")
    readonly property var agreeTerms: qsTr("I agree with MEGA [a]Terms of service.[/a]")
    readonly property var backup: qsTr("Backup")
    readonly property var backupButtonDescription: qsTr("Automatically update your files from your computers to MEGA cloud. Files in your computer won’t be affected by the cloud.")
    readonly property var backupFolders: qsTr("Backup Folders")
    readonly property var backupTo: qsTr("Backup to:")
    readonly property var cancel: qsTr("Cancel")
    readonly property var choose: qsTr("Choose")
    readonly property var computerName: qsTr("Computer name")
    readonly property var computerNameDescription: qsTr("You can assign the name for personal use or workgroup membership of this computer.")
    readonly property var computerNameTitle: qsTr("Set up MEGA")
    readonly property var confirm: qsTr("Confirm")
    readonly property var confirmBackupFoldersDescription: qsTr("Will be added to your cloud and available in your other devices.")
    readonly property var confirmBackupFoldersTitle: qsTr("Confirm folders to back up")
    readonly property var confirmPassword: qsTr("Confirm password")
    readonly property var done: qsTr("Done")
    readonly property var email: qsTr("Email")
    readonly property var errorConfirmPassword: qsTr("Please confirm your password.")
    readonly property var errorEmptyPassword: qsTr("Please enter your password.")
    readonly property var errorFirstLastName: qsTr("Please enter your first and last name.")
    readonly property var errorLogin: qsTr("Invalid email or password. Please try again.")
    readonly property var errorPasswordsMatch: qsTr("Passwords don’t match. Check and try again.")
    readonly property var errorValidEmail: qsTr("Please enter a valid email address.")
    readonly property var firstName: qsTr("First name")
    readonly property var fullSyncButtonDescription: qsTr("Sync your entire Cloud Drive.")
    readonly property var fullSyncTitle: qsTr("Full Sync")
    readonly property var fullSyncDescription: qsTr("Your entire Cloud Drive will be synchronized with a local folder")
    readonly property var forgotPassword: qsTr("Forgot password?")
    readonly property var fuse: qsTr("Fuse")
    readonly property var fuseButtonDescription: qsTr("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
    readonly property var installationType: qsTr("Installation type")
    readonly property var installationTypeDescription: qsTr("Choose a installation type")
    readonly property var installationTypeTitle: qsTr("Choose how you want to use MEGA")
    readonly property var lastName: qsTr("Last name")
    readonly property var login: qsTr("Login")
    readonly property var loginTitle: qsTr("Login into your [b]MEGA account[/b]")
    readonly property var next: qsTr("Next")
    readonly property var notNow: qsTr("Not now")
    readonly property var openInPreferences: qsTr("Open in Preferences")
    readonly property var password: qsTr("Password")
    readonly property var previous: qsTr("Previous")
    readonly property var selectAll: qsTr("[b]Select all[/b]");
    readonly property var selectBackupFoldersTitle: qsTr("Select folders to back up")
    readonly property var selectBackupFoldersDescription: qsTr("Selected folders from your computer to MEGA. Files will automatically back up when the desktop application is running.")
    readonly property var selectFolders: qsTr("Select folders")
    readonly property var selectLocalFolder: qsTr("Select a local folder")
    readonly property var selectMEGAFolder: qsTr("Select a MEGA folder")
    readonly property var selectiveSyncButtonDescription: qsTr("Sync specific folders in your Cloud Drive.")
    readonly property var selectiveSyncDescription: qsTr("Lorem ipsum dolor asitmet")
    readonly property var selectiveSyncTitle: qsTr("Selective Sync")
    readonly property var signUp: qsTr("Sign up")
    readonly property var signUpTitle: qsTr("Create your [b]MEGA account[/b]")
    readonly property var storageSpace: qsTr("Storage space")
    readonly property var synchronize: qsTr("Synchronize")
    readonly property var syncButtonDescription: qsTr("Sync your files between your computers with MEGA cloud, any change from one side will apply to another side.")
    readonly property var syncDescription: qsTr("Lorem ipsum dolor asitmet")
    readonly property var syncTitle: qsTr("Choose sync type")
    readonly property var sync: qsTr("Sync")
    readonly property var twoFANeedHelp: qsTr("I need help")
    readonly property var twoFASubtitle: qsTr("Enter the 6-digit Google Authenticator code for this account")
    readonly property var twoFATitle: qsTr("Continue with [b]two factor authentication[/b]")
    readonly property var understandLossPassword: qsTr("I understand that if [b]I lose my password, I may lose my data[/b]. Read more about [a]MEGA’s end-to-end encryption.[/a]")

}
