pragma Singleton
import QtQuick 2.12

QtObject {

    // !!!!!!!!!!!!!!!!!!!!!!!!!
    //   Sorted alphabetically
    // !!!!!!!!!!!!!!!!!!!!!!!!!

    readonly property var accountTypeFree: qsTr("Free")
    readonly property var accountTypeProI: qsTr("Pro I")
    readonly property var accountTypeProII: qsTr("Pro II")
    readonly property var accountTypeProIII: qsTr("Pro III")
    readonly property var accountTypeLite: qsTr("Pro Lite")
    readonly property var accountTypeBusiness: qsTr("Business")
    readonly property var accountTypeProFlexi: qsTr("Pro Flexi")
    readonly property var addFolders: qsTr("Add folders")
    readonly property var agreeTerms: qsTr("I agree with MEGA [a]Terms of service.[/a]")
    readonly property var backup: qsTr("Backup")
    readonly property var backupButtonDescription: qsTr("Automatically update your files from your computers to MEGA cloud. Files in your computer won’t be affected by the cloud.")
    readonly property var bakupFolderExistsError: qsTr("A folder named \"<folder name>\" already exists in your Backups.")
    readonly property var backupFolders: qsTr("Backup Folders")
    readonly property var backupTo: qsTr("Backup to:")
    readonly property var cancel: qsTr("Cancel")
    readonly property var change: qsTr("Change")
    readonly property var changeEmailBodyText: qsTr("Please enter your new email address. Lorem ipsum dolor explaining that the old email will be substituted.")
    readonly property var changeEmailTitle: qsTr("User another email")
    readonly property var computerName: qsTr("Computer name")
    readonly property var computerNameDescription: qsTr("You can assign the name for personal use or workgroup membership of this computer.")
    readonly property var computerNameTitle: qsTr("Set up MEGA")
    readonly property var confirm: qsTr("Confirm")
    readonly property var confirmBackupErrorDuplicated: qsTr("There is already a folder named \"<backup name>\" in this backup")
    readonly property var confirmBackupErrorRemote: qsTr("A folder named \"<backup name>\" already exists on your backups")
    readonly property var confirmBackupFoldersDescription: qsTr("Will be added to your cloud and available in your other devices.")
    readonly property var confirmBackupFoldersTitle: qsTr("Confirm folders to back up")
    readonly property var confirmEmailTitle: qsTr("Welcome to [b]MEGA[/b]")
    readonly property var confirmEmailBodyText: qsTr("We created an account for you. Please validate your email address in order to get started.")
    readonly property var confirmEmailChangeText: qsTr("If you have misspelled your email address, please [a]click here[/a] to change it.")
    readonly property var confirmPassword: qsTr("Confirm password")
    readonly property var done: qsTr("Done")
    readonly property var email: qsTr("Email")
    readonly property var errorConfirmPassword: qsTr("Please confirm your password.")
    readonly property var errorEmptyPassword: qsTr("Please enter your password.")
    readonly property var errorFirstLastName: qsTr("Please enter your first and last name.")
    readonly property var errorLogin: qsTr("Invalid email or password. Please try again.")
    readonly property var errorPasswordsMatch: qsTr("Passwords don’t match. Check and try again.")
    readonly property var errorValidEmail: qsTr("Please enter a valid email address.")
    readonly property var errorEmailAlreadyExist: qsTr("User already exist")
    readonly property var firstName: qsTr("First name")
    readonly property var fullSyncButtonDescription: qsTr("Sync your entire Cloud Drive.")
    readonly property var fullSyncTitle: qsTr("Full Sync")
    readonly property var fullSyncDescription: qsTr("Your entire Cloud Drive will be synchronized with a local folder")
    readonly property var forgotPassword: qsTr("Forgot password?")
    readonly property var installationType: qsTr("Installation type")
    readonly property var installationTypeDescription: qsTr("Choose a installation type")
    readonly property var installationTypeTitle: qsTr("Choose how you want to use MEGA")
    readonly property var lastName: qsTr("Last name")
    readonly property var login: qsTr("Login")
    readonly property var loginTitle: qsTr("Login into your [b]MEGA account[/b]")
    readonly property var next: qsTr("Next")
    readonly property var notNow: qsTr("Not now")
    readonly property var openInPreferences: qsTr("Open in Preferences")
    readonly property var password: qsTr("Password")
    readonly property var previous: qsTr("Previous")
    readonly property var rename: qsTr("Rename")
    readonly property var resend: qsTr("Resend")
    readonly property var selectAll: qsTr("[b]Select all[/b]");
    readonly property var selectBackupFoldersTitle: qsTr("Select folders to back up")
    readonly property var selectBackupFoldersDescription: qsTr("Selected folders from your computer to MEGA. Files will automatically back up when the desktop application is running.")
    readonly property var selectFolders: qsTr("Select folders")
    readonly property var selectLocalFolder: qsTr("Select a local folder")
    readonly property var selectMEGAFolder: qsTr("Select a MEGA folder")
    readonly property var selectiveSyncButtonDescription: qsTr("Sync specific folders in your Cloud Drive.")
    readonly property var selectiveSyncDescription: qsTr("Lorem ipsum dolor asitmet")
    readonly property var selectiveSyncTitle: qsTr("Selective Sync")
    readonly property var signUp: qsTr("Sign up")
    readonly property var signUpTitle: qsTr("Create your [b]MEGA account[/b]")
    readonly property var storageSpace: qsTr("Storage space")
    readonly property var synchronize: qsTr("Synchronize")
    readonly property var syncButtonDescription: qsTr("Sync your files between your computers with MEGA cloud, any change from one side will apply to another side.")
    readonly property var syncDescription: qsTr("Lorem ipsum dolor asitmet")
    readonly property var syncTitle: qsTr("Choose sync type")
    readonly property var sync: qsTr("Sync")
    readonly property var twoFANeedHelp: qsTr("I need help")
    readonly property var twoFASubtitle: qsTr("Enter the 6-digit Google Authenticator code for this account")
    readonly property var twoFATitle: qsTr("Continue with [b]two factor authentication[/b]")
    readonly property var understandLossPassword: qsTr("I understand that if [b]I lose my password, I may lose my data[/b]. Read more about [a]MEGA’s end-to-end encryption.[/a]")
    readonly property var tooWeakPasswordTitle: qsTr("Too weak")
    readonly property var tooWeakPasswordText: qsTr("Your password needs to be at least 8 characters long.")
    readonly property var weakPasswordTitle: qsTr("Weak")
    readonly property var weakPasswordText: qsTr("Your password is easily guessed. Try making your password longer. Combine uppercase and lowercase letters. Add special characters. Do not use names or dictionary words.")
    readonly property var averagePasswordTitle: qsTr("Average")
    readonly property var averagePasswordText: qsTr("Your password is good enough to proceed, but it is recommended to strengthen it further.")
    readonly property var strongPasswordTitle: qsTr("Strong")
    readonly property var strongPasswordText: qsTr("This password will withstand most typical brute-force attacks. Please ensure that you will remember it.")
    readonly property var excelentPasswordTitle: qsTr("Excellent")
    readonly property var excelentPasswordText: qsTr("This password will withstand most sophisticated brute-force attacks. Please ensure that you will remember it.")
    readonly property var statusLogin: qsTr("Logging in...")
    readonly property var statusFetchNodes: qsTr("Fetching file list...")
    readonly property var statusSignUp: qsTr("Creating account...")
    readonly property var status2FA: qsTr("Validating 2FA code...")
    readonly property var myComputer: qsTr("My Computer")
}
